import { type EmojiDefinition } from "./types";

export enum AnimalsAndNatureEmojis {
  MONKEY_FACE = "monkey_face",
  MONKEY = "monkey",
  GORILLA = "gorilla",
  ORANGUTAN = "orangutan",
  DOG_FACE = "dog_face",
  DOG = "dog",
  GUIDE_DOG = "guide_dog",
  SERVICE_DOG = "service_dog",
  POODLE = "poodle",
  WOLF = "wolf",
  FOX = "fox",
  RACOON = "racoon",
  CAT_FACE = "cat_face",
  CAT = "cat",
  BLACK_CAT = "black_cat",
  LION = "lion",
  TIGER_FACE = "tiger_face",
  TIGER = "tiger",
  LEOPARD = "leopard",
  HORSE_FACE = "horse_face",
  HORSE = "horse",
  UNICORN = "unicorn",
  ZEBRA = "zebra",
  DEER = "deer",
  BISON = "bison",
  COW_FACE = "cow_face",
  COW = "cow",
  OX = "ox",
  WATER_BUFFALO = "water_buffalo",
  PIG_FACE = "pig_face",
  PIG = "pig",
  BOAR = "boar",
  PIG_NOSE = "pig_nose",
  RAM = "ram",
  EWE = "ewe",
  GOAT = "goat",
  CAMEL = "camel",
  TWO_HUMP_CAMEL = "two_hump_camel",
  LLAMA = "llama",
  GIRAFFE = "giraffe",
  ELEPHANT = "elephant",
  MAMMOTH = "mammoth",
  RHINOCEROS = "rhinoceros",
  HIPPOPOTAMUS = "hippopotamus",
  MOUSE_FACE = "mouse_face",
  MOUSE = "mouse",
  RAT = "rat",
  HAMSTER = "hamster",
  RABBIT_FACE = "rabbit_face",
  RABBIT = "rabbit",
  CHIPMUNK = "chipmunk",
  BEAVER = "beaver",
  HEDGEHOG = "hedgehog",
  BAT = "bat",
  BEAR = "bear",
  POLAR_BEAR = "polar_bear",
  KOALA = "koala",
  PANDA = "panda",
  SLOTH = "sloth",
  OTTER = "otter",
  SKUNK = "skunk",
  KANGAROO = "kangaroo",
  BADGER = "badger",
  PAW_PRINTS = "paw_prints",
  TURKEY = "turkey",
  CHICKEN = "chicken",
  ROOSTER = "rooster",
  HATCHING = "hatching",
  BABY_CHICK = "baby_chick",
  FRONT_FACING_CHICK = "front_facing_chick",
  BIRD = "bird",
  BLACK_BIRD = "black_bird",
  PENGUIN = "penguin",
  DOVE = "dove",
  EAGLE = "eagle",
  DUCK = "duck",
  SWAN = "swan",
  OWL = "owl",
  DODO = "dodo",
  FEATHER = "feather",
  FLAMINGO = "flamingo",
  PEACOCK = "peacock",
  FROG = "frog",
  CROCODILE = "crocodile",
  TURTLE = "turtle",
  LIZARD = "lizard",
  SNAKE = "snake",
  DRAGON_FACE = "dragon_face",
  DRAGON = "dragon",
  SAUROPOD = "sauropod",
  T_REX = "t_rex",
  SPOUTING_WHALE = "spouting_whale",
  WHALE = "whale",
  DOLPHIN = "dolphin",
  SEAL = "seal",
  FISH = "fish",
  TROPICAL_FISH = "tropical_fish",
  BLOWFISH = "blowfish",
  SHARK = "shark",
  OCTOPUS = "octopus",
  SPIRAL_SHELL = "spiral_shell",
  SNAIL = "snail",
  BUTTERFLY = "butterfly",
  BUG = "bug",
  ANT = "ant",
  HONEYBEE = "honeybee",
  BEETLE = "beetle",
  LADY_BEETLE = "lady_beetle",
  CRICKET = "cricket",
  COCKROACH = "cockroach",
  SPIDER = "spider",
  SPIDER_WEB = "spider_web",
  SCORPION = "scorpion",
  MOSQUITO = "mosquito",
  FLY = "fly",
  WORM = "worm",
  MICROBE = "microbe",
  BOUQUET = "bouquet",
  CHERRY_BLOSSOM = "cherry_blossom",
  WHITE_FLOWER = "white_flower",
  ROSETTE = "rosette",
  ROSE = "rose",
  WILTED_FLOWER = "wilted_flower",
  HIBISCUS = "hibiscus",
  SUNFLOWER = "sunflower",
  BLOSSOM = "blossom",
  TULIP = "tulip",
  SEEDLING = "seedling",
  POTTED_PLANT = "potted_plant",
  EVERGREEN_TREE = "evergreen_tree",
  DECIDUOUS_PLANT = "deciduous_plant",
  PALM_TREE = "palm_tree",
  CACTUS = "cactus",
  SHEAF_OF_RICE = "sheaf_of_rice",
  HERB = "herb",
  SHAMROCK = "shamrock",
  FOUR_LEAF_CLOVER = "four_leaf_clover",
  MAPLE_LEAF = "maple_leaf",
  FALLEN_LEAF = "fallen_leaf",
  LEAF_FLUTTERING_IN_WIND = "leaf_fluttering_in_wind",
  EMPTY_NEST = "empty_nest",
  NEST_WITH_EGGS = "nest_with_eggs",
}

export const animalsAndNatureEmojis: Record<AnimalsAndNatureEmojis, EmojiDefinition> = {
  [AnimalsAndNatureEmojis.MONKEY_FACE]: { name: "Monkey face", unicode: "U+1F435", emoji: "🐵" },
  [AnimalsAndNatureEmojis.MONKEY]: { name: "Monkey", unicode: "U+1F412", emoji: "🐒" },
  [AnimalsAndNatureEmojis.GORILLA]: { name: "Gorilla", unicode: "U+1F98D", emoji: "🦍" },
  [AnimalsAndNatureEmojis.ORANGUTAN]: { name: "Orangutan", unicode: "U+1F9A7", emoji: "🦧" },
  [AnimalsAndNatureEmojis.DOG_FACE]: { name: "Dog face", unicode: "U+1F436", emoji: "🐶" },
  [AnimalsAndNatureEmojis.DOG]: { name: "Dog", unicode: "U+1F415", emoji: "🐕" },
  [AnimalsAndNatureEmojis.GUIDE_DOG]: { name: "Guide dog", unicode: "U+1F9AE", emoji: "🦮" },
  [AnimalsAndNatureEmojis.SERVICE_DOG]: { name: "Service dog", unicode: "U+1F415 U+200D U+1F9BA", emoji: "🐕‍🦺" },
  [AnimalsAndNatureEmojis.POODLE]: { name: "Poodle", unicode: "U+1F429", emoji: "🐩" },
  [AnimalsAndNatureEmojis.WOLF]: { name: "Wolf", unicode: "U+1F43A", emoji: "🐺" },
  [AnimalsAndNatureEmojis.FOX]: { name: "Fox", unicode: "U+1F98A", emoji: "🦊" },
  [AnimalsAndNatureEmojis.RACOON]: { name: "Racoon", unicode: "U+1F99D", emoji: "🦝" },
  [AnimalsAndNatureEmojis.CAT_FACE]: { name: "Cat face", unicode: "U+1F431", emoji: "🐱" },
  [AnimalsAndNatureEmojis.CAT]: { name: "Cat", unicode: "U+1F408", emoji: "🐈" },
  [AnimalsAndNatureEmojis.BLACK_CAT]: { name: "Black Cat", unicode: "U+1F408 U+200D U+2B1B", emoji: "🐈‍⬛" },
  [AnimalsAndNatureEmojis.LION]: { name: "Lion", unicode: "U+1F981", emoji: "🦁" },
  [AnimalsAndNatureEmojis.TIGER_FACE]: { name: "Tiger face", unicode: "U+1F42F", emoji: "🐯" },
  [AnimalsAndNatureEmojis.TIGER]: { name: "Tiger", unicode: "U+1F405", emoji: "🐅" },
  [AnimalsAndNatureEmojis.LEOPARD]: { name: "Leopard", unicode: "U+1F406", emoji: "🐆" },
  [AnimalsAndNatureEmojis.HORSE_FACE]: { name: "Horse face", unicode: "U+1F434", emoji: "🐴" },
  [AnimalsAndNatureEmojis.HORSE]: { name: "Horse", unicode: "U+1F40E", emoji: "🐎" },
  [AnimalsAndNatureEmojis.UNICORN]: { name: "Unicorn", unicode: "U+1F984", emoji: "🦄" },
  [AnimalsAndNatureEmojis.ZEBRA]: { name: "Zebra", unicode: "U+1F993", emoji: "🦓" },
  [AnimalsAndNatureEmojis.DEER]: { name: "Deer", unicode: "U+1F98C", emoji: "🦌" },
  [AnimalsAndNatureEmojis.BISON]: { name: "Bison", unicode: "U+1F9AC", emoji: "🦬" },
  [AnimalsAndNatureEmojis.COW_FACE]: { name: "Cow face", unicode: "U+1F42E", emoji: "🐮" },
  [AnimalsAndNatureEmojis.COW]: { name: "Cow", unicode: "U+1F404", emoji: "🐄" },
  [AnimalsAndNatureEmojis.OX]: { name: "Ox", unicode: "U+1F402", emoji: "🐂" },
  [AnimalsAndNatureEmojis.WATER_BUFFALO]: { name: "Water buffalo", unicode: "U+1F437", emoji: "🐃" },
  [AnimalsAndNatureEmojis.PIG_FACE]: { name: "Pig face", unicode: "U+1F437", emoji: "🐷" },
  [AnimalsAndNatureEmojis.PIG]: { name: "Pig", unicode: "U+1F416", emoji: "🐖" },
  [AnimalsAndNatureEmojis.BOAR]: { name: "Boar", unicode: "U+1F417", emoji: "🐗" },
  [AnimalsAndNatureEmojis.PIG_NOSE]: { name: "Pig nose", unicode: "U+1F43D", emoji: "🐽" },
  [AnimalsAndNatureEmojis.RAM]: { name: "Ram", unicode: "U+1F40F", emoji: "🐏" },
  [AnimalsAndNatureEmojis.EWE]: { name: "Ewe", unicode: "U+1F411", emoji: "🐑" },
  [AnimalsAndNatureEmojis.GOAT]: { name: "Goat", unicode: "U+1F410", emoji: "🐐" },
  [AnimalsAndNatureEmojis.CAMEL]: { name: "Camel", unicode: "U+1F42A", emoji: "🐪" },
  [AnimalsAndNatureEmojis.TWO_HUMP_CAMEL]: { name: "Two hump camel", unicode: "U+1F42B", emoji: "🐫" },
  [AnimalsAndNatureEmojis.LLAMA]: { name: "Llama", unicode: "U+1F999", emoji: "🦙" },
  [AnimalsAndNatureEmojis.GIRAFFE]: { name: "Giraffe", unicode: "U+1F992", emoji: "🦒" },
  [AnimalsAndNatureEmojis.ELEPHANT]: { name: "Elephant", unicode: "U+1F418", emoji: "🐘" },
  [AnimalsAndNatureEmojis.MAMMOTH]: { name: "Mammoth", unicode: "U+1F9A3", emoji: "🦣" },
  [AnimalsAndNatureEmojis.RHINOCEROS]: { name: "Rhinoceros", unicode: "U+1F98F", emoji: "🦏" },
  [AnimalsAndNatureEmojis.HIPPOPOTAMUS]: { name: "Hippopotamus", unicode: "U+1F99B", emoji: "🦛" },
  [AnimalsAndNatureEmojis.MOUSE_FACE]: { name: "Mouse face", unicode: "U+1F42D", emoji: "🐭" },
  [AnimalsAndNatureEmojis.MOUSE]: { name: "Mouse", unicode: "U+1F401", emoji: "🐁" },
  [AnimalsAndNatureEmojis.RAT]: { name: "Rat", unicode: "U+1F400", emoji: "🐀" },
  [AnimalsAndNatureEmojis.HAMSTER]: { name: "Hamster", unicode: "U+1F439", emoji: "🐹" },
  [AnimalsAndNatureEmojis.RABBIT_FACE]: { name: "Rabbit face", unicode: "U+1F430", emoji: "🐰" },
  [AnimalsAndNatureEmojis.RABBIT]: { name: "Rabbit", unicode: "U+1F407", emoji: "🐇" },
  [AnimalsAndNatureEmojis.CHIPMUNK]: { name: "Chipmunk", unicode: "U+1F43F", emoji: "🐿" },
  [AnimalsAndNatureEmojis.BEAVER]: { name: "Beaver", unicode: "U+1F9AB", emoji: "🦫" },
  [AnimalsAndNatureEmojis.HEDGEHOG]: { name: "Hedgehog", unicode: "U+1F994", emoji: "🦔" },
  [AnimalsAndNatureEmojis.BAT]: { name: "Bat", unicode: "U+1F987", emoji: "🦇" },
  [AnimalsAndNatureEmojis.BEAR]: { name: "Bear", unicode: "U+1F43B", emoji: "🐻" },
  [AnimalsAndNatureEmojis.POLAR_BEAR]: { name: "Polar bear", unicode: "U+1F43B U+200D U+2744 U+FE0F", emoji: "🐻‍❄️" },
  [AnimalsAndNatureEmojis.KOALA]: { name: "Koala", unicode: "U+1F428", emoji: "🐨" },
  [AnimalsAndNatureEmojis.PANDA]: { name: "Panda", unicode: "U+1F43C", emoji: "🐼" },
  [AnimalsAndNatureEmojis.SLOTH]: { name: "Sloth", unicode: "U+1F9A5", emoji: "🦥" },
  [AnimalsAndNatureEmojis.OTTER]: { name: "Otter", unicode: "U+1F9A6", emoji: "🦦" },
  [AnimalsAndNatureEmojis.SKUNK]: { name: "Skunk", unicode: "U+1F9A8", emoji: "🦨" },
  [AnimalsAndNatureEmojis.KANGAROO]: { name: "Kangaroo", unicode: "U+1F998", emoji: "🦘" },
  [AnimalsAndNatureEmojis.BADGER]: { name: "Badger", unicode: "U+1F9A1", emoji: "🦡" },
  [AnimalsAndNatureEmojis.PAW_PRINTS]: { name: "Paw prints", unicode: "U+1F43E", emoji: "🐾" },
  [AnimalsAndNatureEmojis.TURKEY]: { name: "Turkey", unicode: "U+1F983", emoji: "🦃" },
  [AnimalsAndNatureEmojis.CHICKEN]: { name: "Chicken", unicode: "U+1F414", emoji: "🐔" },
  [AnimalsAndNatureEmojis.ROOSTER]: { name: "Rooster", unicode: "U+1F413", emoji: "🐓" },
  [AnimalsAndNatureEmojis.HATCHING]: { name: "Hatching", unicode: "U+1F423", emoji: "🐣" },
  [AnimalsAndNatureEmojis.BABY_CHICK]: { name: "Baby chick", unicode: "U+1F424", emoji: "🐤" },
  [AnimalsAndNatureEmojis.FRONT_FACING_CHICK]: { name: "Front-facing chick", unicode: "U+1F425", emoji: "🐥" },
  [AnimalsAndNatureEmojis.BIRD]: { name: "Bird", unicode: "U+1F426", emoji: "🐦" },
  [AnimalsAndNatureEmojis.BLACK_BIRD]: { name: "Black bird", unicode: "U+1F426 U+200D U+2B1B", emoji: "🐦‍⬛" },
  [AnimalsAndNatureEmojis.PENGUIN]: { name: "Penguin", unicode: "U+1F427", emoji: "🐧" },
  [AnimalsAndNatureEmojis.DOVE]: { name: "Dove", unicode: "U+1F54A", emoji: "🕊" },
  [AnimalsAndNatureEmojis.EAGLE]: { name: "Eagle", unicode: "U+1F985", emoji: "🦅" },
  [AnimalsAndNatureEmojis.DUCK]: { name: "Duck", unicode: "U+1F986", emoji: "🦆" },
  [AnimalsAndNatureEmojis.SWAN]: { name: "Swan", unicode: "U+1F9A2", emoji: "🦢" },
  [AnimalsAndNatureEmojis.OWL]: { name: "Owl", unicode: "U+1F989", emoji: "🦉" },
  [AnimalsAndNatureEmojis.DODO]: { name: "Dodo", unicode: "U+1F9A4", emoji: "🦤" },
  [AnimalsAndNatureEmojis.FEATHER]: { name: "Feather", unicode: "U+1FAB6", emoji: "🪶" },
  [AnimalsAndNatureEmojis.FLAMINGO]: { name: "Flamingo", unicode: "U+1F9A9", emoji: "🦩" },
  [AnimalsAndNatureEmojis.PEACOCK]: { name: "Peacock", unicode: "U+1F99C", emoji: "🦜" },
  [AnimalsAndNatureEmojis.FROG]: { name: "Frog", unicode: "U+1F438", emoji: "🐸" },
  [AnimalsAndNatureEmojis.CROCODILE]: { name: "Crocodile", unicode: "U+1F40A", emoji: "🐊" },
  [AnimalsAndNatureEmojis.TURTLE]: { name: "Turtle", unicode: "U+1F422", emoji: "🐢" },
  [AnimalsAndNatureEmojis.LIZARD]: { name: "Lizard", unicode: "U+1F98E", emoji: "🦎" },
  [AnimalsAndNatureEmojis.SNAKE]: { name: "Snake", unicode: "U+1F40D", emoji: "🐍" },
  [AnimalsAndNatureEmojis.DRAGON_FACE]: { name: "Dragon face", unicode: "U+1F432", emoji: "🐲" },
  [AnimalsAndNatureEmojis.DRAGON]: { name: "Dragon", unicode: "U+1F409", emoji: "🐉" },
  [AnimalsAndNatureEmojis.SAUROPOD]: { name: "Sauropod", unicode: "U+1F995", emoji: "🦕" },
  [AnimalsAndNatureEmojis.T_REX]: { name: "Tyrannosaurus", unicode: "U+1F996", emoji: "🦖" },
  [AnimalsAndNatureEmojis.SPOUTING_WHALE]: { name: "Spouting whale", unicode: "U+1F433", emoji: "🐳" },
  [AnimalsAndNatureEmojis.WHALE]: { name: "Whale", unicode: "U+1F40B", emoji: "🐋" },
  [AnimalsAndNatureEmojis.DOLPHIN]: { name: "Dolphin", unicode: "U+1F42C", emoji: "🐬" },
  [AnimalsAndNatureEmojis.SEAL]: { name: "Seal", unicode: "U+1F9AD", emoji: "🦭" },
  [AnimalsAndNatureEmojis.FISH]: { name: "Fish", unicode: "U+1F41F", emoji: "🐟" },
  [AnimalsAndNatureEmojis.TROPICAL_FISH]: { name: "Tropical fish", unicode: "U+1F420", emoji: "🐠" },
  [AnimalsAndNatureEmojis.BLOWFISH]: { name: "Blowfish", unicode: "U+1F421", emoji: "🐡" },
  [AnimalsAndNatureEmojis.SHARK]: { name: "Shark", unicode: "U+1F988", emoji: "🦈" },
  [AnimalsAndNatureEmojis.OCTOPUS]: { name: "Octopus", unicode: "U+1F419", emoji: "🐙" },
  [AnimalsAndNatureEmojis.SPIRAL_SHELL]: { name: "Spiral shell", unicode: "U+1F41A", emoji: "🐚" },
  [AnimalsAndNatureEmojis.SNAIL]: { name: "Snail", unicode: "U+1F40C", emoji: "🐌" },
  [AnimalsAndNatureEmojis.BUTTERFLY]: { name: "Butterfly", unicode: "U+1F98B", emoji: "🦋" },
  [AnimalsAndNatureEmojis.BUG]: { name: "Bug", unicode: "U+1F41B", emoji: "🐛" },
  [AnimalsAndNatureEmojis.ANT]: { name: "Ant", unicode: "U+1F41C", emoji: "🐜" },
  [AnimalsAndNatureEmojis.HONEYBEE]: { name: "Honeybee", unicode: "U+1F41D", emoji: "🐝" },
  [AnimalsAndNatureEmojis.BEETLE]: { name: "Beetle", unicode: "U+1FAB2", emoji: "🪲" },
  [AnimalsAndNatureEmojis.LADY_BEETLE]: { name: "Lady Beetle", unicode: "U+1F41E", emoji: "🐞" },
  [AnimalsAndNatureEmojis.CRICKET]: { name: "Cricket", unicode: "U+1F997", emoji: "🦗" },
  [AnimalsAndNatureEmojis.COCKROACH]: { name: "Cockroach", unicode: "U+1FAB3", emoji: "🪳" },
  [AnimalsAndNatureEmojis.SPIDER]: { name: "Spider", unicode: "U+1F577", emoji: "🕷" },
  [AnimalsAndNatureEmojis.SPIDER_WEB]: { name: "Spider web", unicode: "U+1F578", emoji: "🕸" },
  [AnimalsAndNatureEmojis.SCORPION]: { name: "Scorpion", unicode: "U+1F982", emoji: "🦂" },
  [AnimalsAndNatureEmojis.MOSQUITO]: { name: "Mosquito", unicode: "U+1F99F", emoji: "🦟" },
  [AnimalsAndNatureEmojis.FLY]: { name: "Fly", unicode: "U+1FAB0", emoji: "🪰" },
  [AnimalsAndNatureEmojis.WORM]: { name: "Worm", unicode: "U+1FAB1", emoji: "🪱" },
  [AnimalsAndNatureEmojis.MICROBE]: { name: "Microbe", unicode: "U+1F9A0", emoji: "🦠" },
  [AnimalsAndNatureEmojis.BOUQUET]: { name: "Bouquet", unicode: "U+1F490", emoji: "💐" },
  [AnimalsAndNatureEmojis.CHERRY_BLOSSOM]: { name: "Cherry blossom", unicode: "U+1F338", emoji: "🌸" },
  [AnimalsAndNatureEmojis.WHITE_FLOWER]: { name: "White flower", unicode: "U+1F4AE", emoji: "💮" },
  [AnimalsAndNatureEmojis.ROSETTE]: { name: "Rosette", unicode: "U+1F3F5", emoji: "🏵" },
  [AnimalsAndNatureEmojis.ROSE]: { name: "Rose", unicode: "U+1F339", emoji: "🌹" },
  [AnimalsAndNatureEmojis.WILTED_FLOWER]: { name: "Wilted flower", unicode: "U+1F940", emoji: "🥀" },
  [AnimalsAndNatureEmojis.HIBISCUS]: { name: "Hibiscus", unicode: "U+1F33A", emoji: "🌺" },
  [AnimalsAndNatureEmojis.SUNFLOWER]: { name: "Sunflower", unicode: "U+1F33B", emoji: "🌻" },
  [AnimalsAndNatureEmojis.BLOSSOM]: { name: "Blossom", unicode: "U+1F33C", emoji: "🌼" },
  [AnimalsAndNatureEmojis.TULIP]: { name: "Tulip", unicode: "U+1F337", emoji: "🌷" },
  [AnimalsAndNatureEmojis.SEEDLING]: { name: "Seedling", unicode: "U+1F331", emoji: "🌱" },
  [AnimalsAndNatureEmojis.POTTED_PLANT]: { name: "Potted plant", unicode: "U+1FAB4", emoji: "🪴" },
  [AnimalsAndNatureEmojis.EVERGREEN_TREE]: { name: "Evergreen tree", unicode: "U+1F332", emoji: "🌲" },
  [AnimalsAndNatureEmojis.DECIDUOUS_PLANT]: { name: "Deciduous plant", unicode: "U+1F333", emoji: "🌳" },
  [AnimalsAndNatureEmojis.PALM_TREE]: { name: "Palm tree", unicode: "U+1F334", emoji: "🌴" },
  [AnimalsAndNatureEmojis.CACTUS]: { name: "Cactus", unicode: "U+1F335", emoji: "🌵" },
  [AnimalsAndNatureEmojis.SHEAF_OF_RICE]: { name: "Sheaf of rice", unicode: "U+1F33E", emoji: "🌾" },
  [AnimalsAndNatureEmojis.HERB]: { name: "Herb", unicode: "U+1F33F", emoji: "🌿" },
  [AnimalsAndNatureEmojis.SHAMROCK]: { name: "Shamrock", unicode: "U+2618", emoji: "☘" },
  [AnimalsAndNatureEmojis.FOUR_LEAF_CLOVER]: { name: "Four leaf clover", unicode: "U+1F340", emoji: "🍀" },
  [AnimalsAndNatureEmojis.MAPLE_LEAF]: { name: "Maple leaf", unicode: "U+1F341", emoji: "🍁" },
  [AnimalsAndNatureEmojis.FALLEN_LEAF]: { name: "Fallen leaf", unicode: "U+1F342", emoji: "🍂" },
  [AnimalsAndNatureEmojis.LEAF_FLUTTERING_IN_WIND]: { name: "Leaf fluttering in wind", unicode: "U+1F343", emoji: "🍃" },
  [AnimalsAndNatureEmojis.EMPTY_NEST]: { name: "Empty nest", unicode: "U+1FAB9", emoji: "🪹" },
  [AnimalsAndNatureEmojis.NEST_WITH_EGGS]: { name: "Nest with eggs", unicode: "U+1FABA", emoji: "🪺" },
}
