import { type EmojiDefinition } from "./types";

export enum ArrowEmojis {
  UP_ARROW = "up_arrow",
  UP_RIGHT_ARROW = "up_right_arrow",
  RIGHT_ARROW = "right_arrow",
  DOWN_RIGHT_ARROW = "down_right_arrow",
  DOWN_ARROW = "down_arrow",
  DOWN_LEFT_ARROW = "down_left_arrow",
  LEFT_ARROW = "left_arrow",
  UP_LEFT_ARROW = "up_left_arrow",
  UP_DOWN_ARROW = "up_down_arrow",
  LEFT_RIGHT_ARROW = "left_right_arrow",
  RIGHT_ARROW_CURVING_LEFT = "right_arrow_curving_left",
  LEFT_ARROW_CURVING_RIGHT = "left_arrow_curving_right",
  RIGHT_ARROW_CURVING_UP = "right_arrow_curving_up",
  RIGHT_ARROW_CURVING_DOWN = "right_arrow_curving_down",
  CLOCKWISE_VERTICAL_ARROW = "clockwise_vertical_arrow",
  COUNTERCLOCKWISE_ARROWS_BUTTON = "counterclockwise_arrows_button",
  BACK_ARROW = "back_arrow",
  END_ARROW = "end_arrow",
  ON_ARROW = "on_arrow",
  SOON_ARROW = "soon_arrow",
  TOP_ARROW = "top_arrow",
}

export const arrowsEmojis: Record<ArrowEmojis, EmojiDefinition> = {
  [ArrowEmojis.UP_ARROW]: { name: "Up Arrow", unicode: "U+2B06", emoji: "⬆" },
  [ArrowEmojis.UP_RIGHT_ARROW]: { name: "Up-right arrow", unicode: "U+2197", emoji: "↗" },
  [ArrowEmojis.RIGHT_ARROW]: { name: "Right arrow", unicode: "U+27A1", emoji: "➡" },
  [ArrowEmojis.DOWN_RIGHT_ARROW]: { name: "Down-right arrow", unicode: "U+2198", emoji: "↘" },
  [ArrowEmojis.DOWN_ARROW]: { name: "Down arrow", unicode: "U+2B07", emoji: "⬇" },
  [ArrowEmojis.DOWN_LEFT_ARROW]: { name: "Down-left arrow", unicode: "U+2199", emoji: "↙" },
  [ArrowEmojis.LEFT_ARROW]: { name: "Left arrow", unicode: "U+2B05", emoji: "⬅" },
  [ArrowEmojis.UP_LEFT_ARROW]: { name: "Up-left arrow", unicode: "U+2196", emoji: "↖" },
  [ArrowEmojis.UP_DOWN_ARROW]: { name: "Up-down arrow", unicode: "U+2195", emoji: "↕" },
  [ArrowEmojis.LEFT_RIGHT_ARROW]: { name: "Left arrow", unicode: "U+2194", emoji: "↔" },
  [ArrowEmojis.RIGHT_ARROW_CURVING_LEFT]: { name: "Right arrow curving left", unicode: "U+21A9", emoji: "↩" },
  [ArrowEmojis.LEFT_ARROW_CURVING_RIGHT]: { name: "Left arrow curving right", unicode: "U+21AA", emoji: "↪" },
  [ArrowEmojis.RIGHT_ARROW_CURVING_UP]: { name: "Right arrow curving up", unicode: "U+2934", emoji: "⤴" },
  [ArrowEmojis.RIGHT_ARROW_CURVING_DOWN]: { name: "Right arrow curving down", unicode: "U+2935", emoji: "⤵" },
  [ArrowEmojis.CLOCKWISE_VERTICAL_ARROW]: { name: "Clockwise vertical arrow", unicode: "U+1F503", emoji: "🔃" },
  [ArrowEmojis.COUNTERCLOCKWISE_ARROWS_BUTTON]: { name: "Counterclockwise arrows button", unicode: "U+1F504", emoji: "🔄" },
  [ArrowEmojis.BACK_ARROW]: { name: "Back arrow", unicode: "U+1F519", emoji: "🔙" },
  [ArrowEmojis.END_ARROW]: { name: "End arrow", unicode: "U+1F51A", emoji: "🔚" },
  [ArrowEmojis.ON_ARROW]: { name: "On arrow", unicode: "U+1F51B", emoji: "🔛" },
  [ArrowEmojis.SOON_ARROW]: { name: "Soon arrow", unicode: "U+1F51C", emoji: "🔜" },
  [ArrowEmojis.TOP_ARROW]: { name: "Top arrow", unicode: "U+1F51D", emoji: "🔝" },
}
