import { type EmojiDefinition } from "./types";

export enum ClothingObjectsEmojis {
  GLASSES = "glasses",
  SUNGLASSES = "sunglasses",
  GOGGLES = "goggles",
  LAB_COAT = "lab_coat",
  SAFETY_VEST = "safety_vest",
  NECKTIE = "necktie",
  T_SHIRT = "t_shirt",
  JEANS = "jeans",
  SCARF = "scarf",
  GLOVES = "gloves",
  COAT = "coat",
  SOCKS = "socks",
  DRESS = "dress",
  KIMONO = "kimono",
  SARI = "sari",
  ONE_PIECE_SUIT = "one_piece_suit",
  BRIEFS = "briefs",
  SHORTS = "shorts",
  BIKINI = "bikini",
  WOMANS_SHIRT = "womans_shirt",
  PURSE = "purse",
  HANDBAG = "handbag",
  CLUTCH_BAG = "clutch_bag",
  SHOPPING_BAGS = "shopping_bags",
  BACKPACK = "backpack",
  THONG_SANDALS = "thong_sandals",
  MANS_SHOE = "mans_shoe",
  RUNNING_SHOE = "running_shoe",
  HIKING_BOOT = "hiking_boot",
  FLAT_SHOE = "flat_shoe",
  HIGH_HEELED_SHOE = "high_heeled_shoe",
  WOMANS_SANDAL = "womans_sandal",
  BALLET_SHOES = "ballet_shoes",
  WOMANS_BOOT = "womans_boot",
  CROWN = "crown",
  WOMANS_HAT = "womans_hat",
  TOP_HAT = "top_hat",
  GRADUATION_CAP = "graduation_cap",
  BILLED_CAP = "billed_cap",
  MILITARY_HELMET = "military_helmet",
  RESCUE_WORKERS_HELMET = "rescue_workers_helmet",
  PRAYER_BEADS = "prayer_beads",
  LIPSTICK = "lipstick",
  RING = "ring",
  GEMSTONE = "gemstone",
}

export const clothingObjectsEmojis: Record<ClothingObjectsEmojis, EmojiDefinition> = {
  [ClothingObjectsEmojis.GLASSES]: { name: "Glasses", unicode: "U+1F453", emoji: "👓" },
  [ClothingObjectsEmojis.SUNGLASSES]: { name: "Sunglasses", unicode: "U+1F576", emoji: "🕶" },
  [ClothingObjectsEmojis.GOGGLES]: { name: "Goggles", unicode: "U+1F97D", emoji: "🥽" },
  [ClothingObjectsEmojis.LAB_COAT]: { name: "Lab coat", unicode: "U+1F97C", emoji: "🥼" },
  [ClothingObjectsEmojis.SAFETY_VEST]: { name: "Safety vest", unicode: "U+1F9BA", emoji: "🦺" },
  [ClothingObjectsEmojis.NECKTIE]: { name: "Necktie", unicode: "U+1F454", emoji: "👔" },
  [ClothingObjectsEmojis.T_SHIRT]: { name: "T-shirt", unicode: "U+1F455", emoji: "👕" },
  [ClothingObjectsEmojis.JEANS]: { name: "Jeans", unicode: "U+1F456", emoji: "👖" },
  [ClothingObjectsEmojis.SCARF]: { name: "Scarf", unicode: "U+1F9E3", emoji: "🧣" },
  [ClothingObjectsEmojis.GLOVES]: { name: "Gloves", unicode: "U+1F9E4", emoji: "🧤" },
  [ClothingObjectsEmojis.COAT]: { name: "Coat", unicode: "U+1F9E5", emoji: "🧥" },
  [ClothingObjectsEmojis.SOCKS]: { name: "Socks", unicode: "U+1F9E6", emoji: "🧦" },
  [ClothingObjectsEmojis.DRESS]: { name: "Dress", unicode: "U+1F457", emoji: "👗" },
  [ClothingObjectsEmojis.KIMONO]: { name: "Kimono", unicode: "U+1F458", emoji: "👘" },
  [ClothingObjectsEmojis.SARI]: { name: "Sari", unicode: "U+1F97B", emoji: "🥻" },
  [ClothingObjectsEmojis.ONE_PIECE_SUIT]: { name: "One piece suit", unicode: "U+1FA71", emoji: "🩱" },
  [ClothingObjectsEmojis.BRIEFS]: { name: "Briefs", unicode: "U+1FA72", emoji: "🩲" },
  [ClothingObjectsEmojis.SHORTS]: { name: "Shorts", unicode: "U+1FA73", emoji: "🩳" },
  [ClothingObjectsEmojis.BIKINI]: { name: "Bikini", unicode: "U+1F459", emoji: "👙" },
  [ClothingObjectsEmojis.WOMANS_SHIRT]: { name: "Woman's shirt", unicode: "U+1F45A", emoji: "👚" },
  [ClothingObjectsEmojis.PURSE]: { name: "Purse", unicode: "U+1F45B", emoji: "👛" },
  [ClothingObjectsEmojis.HANDBAG]: { name: "Handbag", unicode: "U+1F45C", emoji: "👜" },
  [ClothingObjectsEmojis.CLUTCH_BAG]: { name: "Clutch bag", unicode: "U+1F45D", emoji: "👝" },
  [ClothingObjectsEmojis.SHOPPING_BAGS]: { name: "Shopping bags", unicode: "U+1F6CD", emoji: "🛍" },
  [ClothingObjectsEmojis.BACKPACK]: { name: "Backpack", unicode: "U+1F392", emoji: "🎒" },
  [ClothingObjectsEmojis.THONG_SANDALS]: { name: "Thong sandals", unicode: "U+1FA74", emoji: "🩴" },
  [ClothingObjectsEmojis.MANS_SHOE]: { name: "Man's shoe", unicode: "U+1F45E", emoji: "👞" },
  [ClothingObjectsEmojis.RUNNING_SHOE]: { name: "Running shoe", unicode: "U+1F45F", emoji: "👟" },
  [ClothingObjectsEmojis.HIKING_BOOT]: { name: "Hiking boot", unicode: "U+1F97E", emoji: "🥾" },
  [ClothingObjectsEmojis.FLAT_SHOE]: { name: "Flat shoe", unicode: "U+1F97F", emoji: "🥿" },
  [ClothingObjectsEmojis.HIGH_HEELED_SHOE]: { name: "High-heeled shoe", unicode: "U+1F460", emoji: "👠" },
  [ClothingObjectsEmojis.WOMANS_SANDAL]: { name: "Woman's sandal", unicode: "U+1F461", emoji: "👡" },
  [ClothingObjectsEmojis.BALLET_SHOES]: { name: "Ballet shoes", unicode: "U+1FA70", emoji: "🩰" },
  [ClothingObjectsEmojis.WOMANS_BOOT]: { name: "Woman's boot", unicode: "U+1F462", emoji: "👢" },
  [ClothingObjectsEmojis.CROWN]: { name: "Crown", unicode: "U+1F451", emoji: "👑" },
  [ClothingObjectsEmojis.WOMANS_HAT]: { name: "Woman's hat", unicode: "U+1F452", emoji: "👒" },
  [ClothingObjectsEmojis.TOP_HAT]: { name: "Top hat", unicode: "U+1F3A9", emoji: "🎩" },
  [ClothingObjectsEmojis.GRADUATION_CAP]: { name: "Graduation cap", unicode: "U+1F393", emoji: "🎓" },
  [ClothingObjectsEmojis.BILLED_CAP]: { name: "Billed cap", unicode: "U+1F9E2", emoji: "🧢" },
  [ClothingObjectsEmojis.MILITARY_HELMET]: { name: "Military helmet", unicode: "U+1FA96", emoji: "🪖" },
  [ClothingObjectsEmojis.RESCUE_WORKERS_HELMET]: { name: "Rescue worker's helmet", unicode: "U+26D1", emoji: "⛑" },
  [ClothingObjectsEmojis.PRAYER_BEADS]: { name: "Prayer beads", unicode: "U+1F4FF", emoji: "📿" },
  [ClothingObjectsEmojis.LIPSTICK]: { name: "Lipstick", unicode: "U+1F484", emoji: "💄" },
  [ClothingObjectsEmojis.RING]: { name: "Ring", unicode: "U+1F48D", emoji: "💍" },
  [ClothingObjectsEmojis.GEMSTONE]: { name: "Gemstone", unicode: "U+1F48E", emoji: "💎" },
}
