import { type EmojiDefinition } from "./types";

export enum CountryFlagsEmojis {
  ASCENSION_ISLAND_FLAG = "ascension_island_flag",
  ANDORRA_FLAG = "andorra_flag",
  UAE_FLAG = "uae_flag",
  AFGHANISTAN_FLAG = "afghanistan_flag",
  ANTIGUA_BARBUDA_FLAG = "antigua_barbuda_flag",
  ANGUILLA_FLAG = "anguilla_flag",
  ALBANIA_FLAG = "albania_flag",
  ALGERIA_FLAG = "algeria_flag",
  ARMENIA_FLAG = "armenia_flag",
  ANGOLA_FLAG = "angola_flag",
  ANTARCTICA_FLAG = "antarctica_flag",
  ARGENTINA_FLAG = "argentina_flag",
  AMERICAN_SAMOA_FLAG = "american_samoa_flag",
  AUSTRIA_FLAG = "austria_flag",
  AUSTRALIA_FLAG = "australia_flag",
  ARUBA_FLAG = "aruba_flag",
  ALAND_ISLANDS_FLAG = "aland_islands_flag",
  AZERBAIJAN_FLAG = "azerbaijan_flag",
  BOSNIA_HERZEGOVINA_FLAG = "bosnia_herzegovina_flag",
  BANGLADESH_FLAG = "bangladesh_flag",
  BELGIUM_FLAG = "belgium_flag",
  BURKINA_FASO_FLAG = "burkina_faso_flag",
  BULGARIA_FLAG = "bulgaria_flag",
  BAHRAIN_FLAG = "bahrain_flag",
  BURUNDI_FLAG = "burundi_flag",
  BENIN_FLAG = "benin_flag",
  ST_BARTHELEMY_FLAG = "st_barthelemy_flag",
  BERMUDA_FLAG = "bermuda_flag",
  BRUNEI_FLAG = "brunei_flag",
  BOLIVIA_FLAG = "bolivia_flag",
  CARIBBEAN_NETHERLANDS_FLAG = "caribbean_netherlands_flag",
  BRAZIL_FLAG = "brazil_flag",
  BAHAMAS_FLAG = "bahamas_flag",
  BHUTAN_FLAG = "bhutan_flag",
  BOUVET_ISLAND_FLAG = "bouvet_island_flag",
  BOTSWANA_FLAG = "botswana_flag",
  BELARUS_FLAG = "belarus_flag",
  BELIZE_FLAG = "belize_flag",
  CANADA_FLAG = "canada_flag",
  COCOS_ISLANDS_FLAG = "cocos_islands_flag",
  DR_CONGO_FLAG = "dr_congo_flag",
  CENTRAL_AFRICAN_REPUBLIC_FLAG = "central_african_republic_flag",
  CONGO_BRAZZAVILLE_FLAG = "congo_brazzaville_flag",
  SWITZERLAND_FLAG = "switzerland_flag",
  COTE_DIVOIRE_FLAG = "cote_divoire_flag",
  COOK_ISLANDS_FLAG = "cook_islands_flag",
  CHILE_FLAG = "chile_flag",
  CAMEROON_FLAG = "cameroon_flag",
  CHINA_FLAG = "china_flag",
  COLOMBIA_FLAG = "colombia_flag",
  CLIPPERTON_ISLAND_FLAG = "clipperton_island_flag",
  COSTA_RICA_FLAG = "costa_rica_flag",
  CUBA_FLAG = "cuba_flag",
  CAPE_VERDE_FLAG = "cape_verde_flag",
  CURACAO_FLAG = "curacao_flag",
  CHRISTMAS_ISLAND_FLAG = "christmas_island_flag",
  CYPRUS_FLAG = "cyprus_flag",
  CZECH_REPUBLIC_FLAG = "czech_republic_flag",
  GERMANY_FLAG = "germany_flag",
  DIEGO_GARCIA_FLAG = "diego_garcia_flag",
  DJIBOUTI_FLAG = "djibouti_flag",
  DENMARK_FLAG = "denmark_flag",
  DOMINICA_FLAG = "dominica_flag",
  DOMINICAN_REPUBLIC_FLAG = "dominican_republic_flag",
  CEUTA_MELILLA_FLAG = "ceuta_melilla_flag",
  ECUADOR_FLAG = "ecuador_flag",
  ESTONIA_FLAG = "estonia_flag",
  EGYPT_FLAG = "egypt_flag",
  WESTERN_SAHARA_FLAG = "western_sahara_flag",
  ERITREA_FLAG = "eritrea_flag",
  SPAIN_FLAG = "spain_flag",
  ETHIOPIA_FLAG = "ethiopia_flag",
  EUROPEAN_UNION_FLAG = "european_union_flag",
  FINLAND_FLAG = "finland_flag",
  FIJI_FLAG = "fiji_flag",
  FALKLAND_ISLANDS_FLAG = "falkland_islands_flag",
  MICRONESIA_FLAG = "micronesia_flag",
  FAROE_ISLANDS_FLAG = "faroe_islands_flag",
  FRANCE_FLAG = "france_flag",
  GABON_FLAG = "gabon_flag",
  UNITED_KINGDOM_FLAG = "united_kingdom_flag",
  GRENADA_FLAG = "grenada_flag",
  GEORGIA_FLAG = "georgia_flag",
  FRENCH_GUIANA_FLAG = "french_guiana_flag",
  GUERNSEY_FLAG = "guernsey_flag",
  GHANA_FLAG = "ghana_flag",
  GIBRALTAR_FLAG = "gibraltar_flag",
  GREENLAND_FLAG = "greenland_flag",
  GAMBIA_FLAG = "gambia_flag",
  GUINEA_FLAG = "guinea_flag",
  GUADELOUPE_FLAG = "guadeloupe_flag",
  EQUATORIAL_GUINEA_FLAG = "equatorial_guinea_flag",
  GREECE_FLAG = "greece_flag",
  SOUTH_GEORGIA_SANDWICH_ISLANDS_FLAG = "south_georgia_sandwich_islands_flag",
  GUATEMALA_FLAG = "guatemala_flag",
  GUAM_FLAG = "guam_flag",
  GUINEA_BISSAU_FLAG = "guinea_bissau_flag",
  GUYANA_FLAG = "guyana_flag",
  HONG_KONG_FLAG = "hong_kong_flag",
  HEARD_MCDONALD_ISLANDS_FLAG = "heard_mcdonald_islands_flag",
  HONDURAS_FLAG = "honduras_flag",
  CROATIA_FLAG = "croatia_flag",
  HAITI_FLAG = "haiti_flag",
  HUNGARY_FLAG = "hungary_flag",
  CANARY_ISLANDS_FLAG = "canary_islands_flag",
  INDONESIA_FLAG = "indonesia_flag",
  IRELAND_FLAG = "ireland_flag",
  ISRAEL_FLAG = "israel_flag",
  ISLE_OF_MAN_FLAG = "isle_of_man_flag",
  INDIA_FLAG = "india_flag",
  BRITISH_INDIAN_OCEAN_TERRITORY_FLAG = "british_indian_ocean_territory_flag",
  IRAQ_FLAG = "iraq_flag",
  IRAN_FLAG = "iran_flag",
  ICELAND_FLAG = "iceland_flag",
  ITALY_FLAG = "italy_flag",
  JERSEY_FLAG = "jersey_flag",
  JAMAICA_FLAG = "jamaica_flag",
  JORDAN_FLAG = "jordan_flag",
  JAPAN_FLAG = "japan_flag",
  KENYA_FLAG = "kenya_flag",
  KYRGYZSTAN_FLAG = "kyrgyzstan_flag",
  CAMBODIA_FLAG = "cambodia_flag",
  KIRIBATI_FLAG = "kiribati_flag",
  COMOROS_FLAG = "comoros_flag",
  ST_KITTS_NEVIS_FLAG = "st_kitts_nevis_flag",
  NORTH_KOREA_FLAG = "north_korea_flag",
  SOUTH_KOREA_FLAG = "south_korea_flag",
  KUWAIT_FLAG = "kuwait_flag",
  CAYMAN_ISLANDS_FLAG = "cayman_islands_flag",
  KAZAKHSTAN_FLAG = "kazakhstan_flag",
  LAOS_FLAG = "laos_flag",
  LEBANON_FLAG = "lebanon_flag",
  ST_LUCIA_FLAG = "st_lucia_flag",
  LIECHTENSTEIN_FLAG = "liechtenstein_flag",
  SRI_LANKA_FLAG = "sri_lanka_flag",
  LIBERIA_FLAG = "liberia_flag",
  LESOTHO_FLAG = "lesotho_flag",
  LITHUANIA_FLAG = "lithuania_flag",
  LUXEMBOURG_FLAG = "luxembourg_flag",
  LATVIA_FLAG = "latvia_flag",
  LIBYA_FLAG = "libya_flag",
  MOROCCO_FLAG = "morocco_flag",
  MONACO_FLAG = "monaco_flag",
  MOLDOVA_FLAG = "moldova_flag",
  MONTENEGRO_FLAG = "montenegro_flag",
  ST_MARTIN_FLAG = "st_martin_flag",
  MADAGASCAR_FLAG = "madagascar_flag",
  MARSHALL_ISLANDS_FLAG = "marshall_islands_flag",
  NORTH_MACEDONIA_FLAG = "north_macedonia_flag",
  MALI_FLAG = "mali_flag",
  MYANMAR_FLAG = "myanmar_flag",
  MONGOLIA_FLAG = "mongolia_flag",
  MACAO_FLAG = "macao_flag",
  NORTHERN_MARIANA_ISLANDS_FLAG = "northern_mariana_islands_flag",
  MARTINIQUE_FLAG = "martinique_flag",
  MAURITANIA_FLAG = "mauritania_flag",
  MONTSERRAT_FLAG = "montserrat_flag",
  MALTA_FLAG = "malta_flag",
  MAURITIUS_FLAG = "mauritius_flag",
  MALDIVES_FLAG = "maldives_flag",
  MALAWI_FLAG = "malawi_flag",
  MEXICO_FLAG = "mexico_flag",
  MALAYSIA_FLAG = "malaysia_flag",
  MOZAMBIQUE_FLAG = "mozambique_flag",
  NAMIBIA_FLAG = "namibia_flag",
  NEW_CALEDONIA_FLAG = "new_caledonia_flag",
  NIGER_FLAG = "niger_flag",
  NIGERIA_FLAG = "nigeria_flag",
  NORFOLK_ISLAND_FLAG = "norfolk_island_flag",
  NICARAGUA_FLAG = "nicaragua_flag",
  NETHERLANDS_FLAG = "netherlands_flag",
  NORWAY_FLAG = "norway_flag",
  NEPAL_FLAG = "nepal_flag",
  NAURU_FLAG = "nauru_flag",
  NIUE_FLAG = "niue_flag",
  NEW_ZEALAND_FLAG = "new_zealand_flag",
  OMAN_FLAG = "oman_flag",
  PANAMA_FLAG = "panama_flag",
  PERU_FLAG = "peru_flag",
  FRENCH_POLYNESIA_FLAG = "french_polynesia_flag",
  PAPUA_NEW_GUINEA_FLAG = "papua_new_guinea_flag",
  PHILIPPINES_FLAG = "philippines_flag",
  PAKISTAN_FLAG = "pakistan_flag",
  POLAND_FLAG = "poland_flag",
  ST_PIERRE_MIQUELON_FLAG = "st_pierre_miquelon_flag",
  PITCAIRN_ISLANDS_FLAG = "pitcairn_islands_flag",
  PUERTO_RICO_FLAG = "puerto_rico_flag",
  PALESTINIAN_TERRITORIES_FLAG = "palestinian_territories_flag",
  PORTUGAL_FLAG = "portugal_flag",
  PALAU_FLAG = "palau_flag",
  PARAGUAY_FLAG = "paraguay_flag",
  QATAR_FLAG = "qatar_flag",
  REUNION_FLAG = "reunion_flag",
  ROMANIA_FLAG = "romania_flag",
  SERBIA_FLAG = "serbia_flag",
  RUSSIA_FLAG = "russia_flag",
  RWANDA_FLAG = "rwanda_flag",
  SAUDI_ARABIA_FLAG = "saudi_arabia_flag",
  SOLOMON_ISLANDS_FLAG = "solomon_islands_flag",
  SEYCHELLES_FLAG = "seychelles_flag",
  SUDAN_FLAG = "sudan_flag",
  SWEDEN_FLAG = "sweden_flag",
  SINGAPORE_FLAG = "singapore_flag",
  ST_HELENA_FLAG = "st_helena_flag",
  SLOVENIA_FLAG = "slovenia_flag",
  SVALBARD_JAN_MAYEN_FLAG = "svalbard_jan_mayen_flag",
  SLOVAKIA_FLAG = "slovakia_flag",
  SIERRA_LEONE_FLAG = "sierra_leone_flag",
  SAN_MARINO_FLAG = "san_marino_flag",
  SENEGAL_FLAG = "senegal_flag",
  SOMALIA_FLAG = "somalia_flag",
  SURINAME_FLAG = "suriname_flag",
  SOUTH_SUDAN_FLAG = "south_sudan_flag",
  SAO_TOME_PRINCIPE_FLAG = "sao_tome_principe_flag",
  EL_SALVADOR_FLAG = "el_salvador_flag",
  SAINT_MAARTEN_FLAG = "saint_maarten_flag",
  SYRIA_FLAG = "syria_flag",
  ESWATINI_FLAG = "eswatini_flag",
  TRISTAN_DA_CUNHA_FLAG = "tristan_da_cunha_flag",
  TURKS_CAICOS_ISLANDS_FLAG = "turks_caicos_islands_flag",
  CHAD_FLAG = "chad_flag",
  FRENCH_SOUTHERN_TERRITORIES_FLAG = "french_southern_territories_flag",
  TOGO_FLAG = "togo_flag",
  THAILAND_FLAG = "thailand_flag",
  TAJIKISTAN_FLAG = "tajikistan_flag",
  TOKELAU_FLAG = "tokelau_flag",
  TIMOR_LESTE_FLAG = "timor_leste_flag",
  TURKMENISTAN_FLAG = "turkmenistan_flag",
  TUNISIA_FLAG = "tunisia_flag",
  TONGA_FLAG = "tonga_flag",
  TURKEY_FLAG = "turkey_flag",
  TRINIDAD_TOBAGO_FLAG = "trinidad_tobago_flag",
  TUVALU_FLAG = "tuvalu_flag",
  TAIWAN_FLAG = "taiwan_flag",
  TANZANIA_FLAG = "tanzania_flag",
  UKRAINE_FLAG = "ukraine_flag",
  UGANDA_FLAG = "uganda_flag",
  US_OUTLYING_ISLANDS_FLAG = "us_outlying_islands_flag",
  UNITED_NATIONS_FLAG = "united_nations_flag",
  UNITED_STATES_FLAG = "united_states_flag",
  URUGUAY_FLAG = "uruguay_flag",
  UZBEKISTAN_FLAG = "uzbekistan_flag",
  VATICAN_CITY_FLAG = "vatican_city_flag",
  ST_VINCENT_GRENADINES_FLAG = "st_vincent_grenadines_flag",
  VENEZUELA_FLAG = "venezuela_flag",
  BRITISH_VIRGIN_ISLANDS_FLAG = "british_virgin_islands_flag",
  US_VIRGIN_ISLANDS_FLAG = "us_virgin_islands_flag",
  VIETNAM_FLAG = "vietnam_flag",
  VANUATU_FLAG = "vanuatu_flag",
  WALLIS_FUTUNA_FLAG = "wallis_futuna_flag",
  SAMOA_FLAG = "samoa_flag",
  KOSOVO_FLAG = "kosovo_flag",
  YEMEN_FLAG = "yemen_flag",
  MAYOTTE_FLAG = "mayotte_flag",
  SOUTH_AFRICA_FLAG = "south_africa_flag",
  ZAMBIA_FLAG = "zambia_flag",
  ZIMBABWE_FLAG = "zimbabwe_flag",
  ENGLAND_FLAG = "england_flag",
  SCOTLAND_FLAG = "scotland_flag",
  WALES_FLAG = "wales_flag",
}

export const countryFlagsEmojis: Record<CountryFlagsEmojis, EmojiDefinition> = {
  [CountryFlagsEmojis.ASCENSION_ISLAND_FLAG]: {
    name: "Ascension Island flag",
    unicode: "U+1F1E6 U+1F1E8",
    emoji: "🇦🇨",
  },
  [CountryFlagsEmojis.ANDORRA_FLAG]: {
    name: "Andorra flag",
    unicode: "U+1F1E6 U+1F1E9",
    emoji: "🇦🇩",
  },
  [CountryFlagsEmojis.UAE_FLAG]: {
    name: "UAE flag",
    unicode: "U+1F1E6 U+1F1EA",
    emoji: "🇦🇪",
  },
  [CountryFlagsEmojis.AFGHANISTAN_FLAG]: {
    name: "Afghanistan flag",
    unicode: "U+1F1E6 U+1F1EB",
    emoji: "🇦🇫",
  },
  [CountryFlagsEmojis.ANTIGUA_BARBUDA_FLAG]: {
    name: "Antigua & Barbuda flag",
    unicode: "U+1F1E6 U+1F1EC",
    emoji: "🇦🇬",
  },
  [CountryFlagsEmojis.ANGUILLA_FLAG]: {
    name: "Anguilla flag",
    unicode: "U+1F1E6 U+1F1EE",
    emoji: "🇦🇮",
  },
  [CountryFlagsEmojis.ALBANIA_FLAG]: {
    name: "Albania flag",
    unicode: "U+1F1E6 U+1F1F1",
    emoji: "🇦🇱",
  },
  [CountryFlagsEmojis.ALGERIA_FLAG]: {
    name: "Algeria flag",
    unicode: "U+1F1E9 U+1F1FF",
    emoji: "🇩🇿",
  },
  [CountryFlagsEmojis.ARMENIA_FLAG]: {
    name: "Armenia flag",
    unicode: "U+1F1E6 U+1F1F2",
    emoji: "🇦🇲",
  },
  [CountryFlagsEmojis.ANGOLA_FLAG]: {
    name: "Angola flag",
    unicode: "U+1F1E6 U+1F1F4",
    emoji: "🇦🇴",
  },
  [CountryFlagsEmojis.ANTARCTICA_FLAG]: {
    name: "Antarctica flag",
    unicode: "U+1F1E6 U+1F1F6",
    emoji: "🇦🇶",
  },
  [CountryFlagsEmojis.ARGENTINA_FLAG]: {
    name: "Argentina flag",
    unicode: "U+1F1E6 U+1F1F7",
    emoji: "🇦🇷",
  },
  [CountryFlagsEmojis.AMERICAN_SAMOA_FLAG]: {
    name: "American Samoa flag",
    unicode: "U+1F1E6 U+1F1F8",
    emoji: "🇦🇸",
  },
  [CountryFlagsEmojis.AUSTRIA_FLAG]: {
    name: "Austria flag",
    unicode: "U+1F1E6 U+1F1F9",
    emoji: "🇦🇹",
  },
  [CountryFlagsEmojis.AUSTRALIA_FLAG]: {
    name: "Australia flag",
    unicode: "U+1F1E6 U+1F1FA",
    emoji: "🇦🇺",
  },
  [CountryFlagsEmojis.ARUBA_FLAG]: {
    name: "Aruba flag",
    unicode: "U+1F1E6 U+1F1FC",
    emoji: "🇦🇼",
  },
  [CountryFlagsEmojis.ALAND_ISLANDS_FLAG]: {
    name: "Åland Islands flag",
    unicode: "U+1F1E6 U+1F1FD",
    emoji: "🇦🇽",
  },
  [CountryFlagsEmojis.AZERBAIJAN_FLAG]: {
    name: "Azerbaijan flag",
    unicode: "U+1F1E6 U+1F1FF",
    emoji: "🇦🇿",
  },
  [CountryFlagsEmojis.BOSNIA_HERZEGOVINA_FLAG]: {
    name: "Bosnia & Herzegovina flag",
    unicode: "U+1F1E7 U+1F1E6",
    emoji: "🇧🇦",
  },
  [CountryFlagsEmojis.BANGLADESH_FLAG]: {
    name: "Bangladesh flag",
    unicode: "U+1F1E7 U+1F1E9",
    emoji: "🇧🇩",
  },
  [CountryFlagsEmojis.BELGIUM_FLAG]: {
    name: "Belgium flag",
    unicode: "U+1F1E7 U+1F1EA",
    emoji: "🇧🇪",
  },
  [CountryFlagsEmojis.BURKINA_FASO_FLAG]: {
    name: "Burkina Faso flag",
    unicode: "U+1F1E7 U+1F1EB",
    emoji: "🇧🇫",
  },
  [CountryFlagsEmojis.BULGARIA_FLAG]: {
    name: "Bulgaria flag",
    unicode: "U+1F1E7 U+1F1EC",
    emoji: "🇧🇬",
  },
  [CountryFlagsEmojis.BAHRAIN_FLAG]: {
    name: "Bahrain flag",
    unicode: "U+1F1E7 U+1F1ED",
    emoji: "🇧🇭",
  },
  [CountryFlagsEmojis.BURUNDI_FLAG]: {
    name: "Burundi flag",
    unicode: "U+1F1E7 U+1F1EE",
    emoji: "🇧🇮",
  },
  [CountryFlagsEmojis.BENIN_FLAG]: {
    name: "Benin Republic flag",
    unicode: "U+1F1E7 U+1F1EF",
    emoji: "🇧🇯",
  },
  [CountryFlagsEmojis.ST_BARTHELEMY_FLAG]: {
    name: "St. Barthélemy flag",
    unicode: "U+1F1E7 U+1F1F1",
    emoji: "🇧🇱",
  },
  [CountryFlagsEmojis.BERMUDA_FLAG]: {
    name: "Bermuda flag",
    unicode: "U+1F1E7 U+1F1F2",
    emoji: "🇧🇲",
  },
  [CountryFlagsEmojis.BRUNEI_FLAG]: {
    name: "Brunei flag",
    unicode: "U+1F1E7 U+1F1F3",
    emoji: "🇧🇳",
  },
  [CountryFlagsEmojis.BOLIVIA_FLAG]: {
    name: "Bolivia flag",
    unicode: "U+1F1E7 U+1F1F4",
    emoji: "🇧🇴",
  },
  [CountryFlagsEmojis.CARIBBEAN_NETHERLANDS_FLAG]: {
    name: "Caribbean Netherlands flag",
    unicode: "U+1F1E7 U+1F1F6",
    emoji: "🇧🇶",
  },
  [CountryFlagsEmojis.BRAZIL_FLAG]: {
    name: "Brazil flag",
    unicode: "U+1F1E7 U+1F1F7",
    emoji: "🇧🇷",
  },
  [CountryFlagsEmojis.BAHAMAS_FLAG]: {
    name: "Bahamas flag",
    unicode: "U+1F1E7 U+1F1F8",
    emoji: "🇧🇸",
  },
  [CountryFlagsEmojis.BHUTAN_FLAG]: {
    name: "Bhutan flag",
    unicode: "U+1F1E7 U+1F1F9",
    emoji: "🇧🇹",
  },
  [CountryFlagsEmojis.BOUVET_ISLAND_FLAG]: {
    name: "Bouvet Island flag",
    unicode: "U+1F1E7 U+1F1FB",
    emoji: "🇧🇻",
  },
  [CountryFlagsEmojis.BOTSWANA_FLAG]: {
    name: "Botswana flag",
    unicode: "U+1F1E7 U+1F1FC",
    emoji: "🇧🇼",
  },
  [CountryFlagsEmojis.BELARUS_FLAG]: {
    name: "Belarus flag",
    unicode: "U+1F1E7 U+1F1FE",
    emoji: "🇧🇾",
  },
  [CountryFlagsEmojis.BELIZE_FLAG]: {
    name: "Belize flag",
    unicode: "U+1F1E7 U+1F1FF",
    emoji: "🇧🇿",
  },
  [CountryFlagsEmojis.CANADA_FLAG]: {
    name: "Canada flag",
    unicode: "U+1F1E8 U+1F1E6",
    emoji: "🇨🇦",
  },
  [CountryFlagsEmojis.COCOS_ISLANDS_FLAG]: {
    name: "Cocos (Keeling) Islands flag",
    unicode: "U+1F1E8 U+1F1E8",
    emoji: "🇨🇨",
  },
  [CountryFlagsEmojis.DR_CONGO_FLAG]: {
    name: "DR Congo flag",
    unicode: "U+1F1E8 U+1F1E9",
    emoji: "🇨🇩",
  },
  [CountryFlagsEmojis.CENTRAL_AFRICAN_REPUBLIC_FLAG]: {
    name: "Central African Republic flag",
    unicode: "U+1F1E8 U+1F1EB",
    emoji: "🇨🇫",
  },
  [CountryFlagsEmojis.CONGO_BRAZZAVILLE_FLAG]: {
    name: "Congo Brazzaville flag",
    unicode: "U+1F1E8 U+1F1EC",
    emoji: "🇨🇬",
  },
  [CountryFlagsEmojis.SWITZERLAND_FLAG]: {
    name: "Switzerland flag",
    unicode: "U+1F1E8 U+1F1ED",
    emoji: "🇨🇭",
  },
  [CountryFlagsEmojis.COTE_DIVOIRE_FLAG]: {
    name: "Côte d’Ivoire flag",
    unicode: "U+1F1E8 U+1F1EE",
    emoji: "🇨🇮",
  },
  [CountryFlagsEmojis.COOK_ISLANDS_FLAG]: {
    name: "Cook Islands flag",
    unicode: "U+1F1E8 U+1F1F0",
    emoji: "🇨🇰",
  },
  [CountryFlagsEmojis.CHILE_FLAG]: {
    name: "Chile flag",
    unicode: "U+1F1E8 U+1F1F1",
    emoji: "🇨🇱",
  },
  [CountryFlagsEmojis.CAMEROON_FLAG]: {
    name: "Cameroon flag",
    unicode: "U+1F1E8 U+1F1F2",
    emoji: "🇨🇲",
  },
  [CountryFlagsEmojis.CHINA_FLAG]: {
    name: "China flag",
    unicode: "U+1F1E8 U+1F1F3",
    emoji: "🇨🇳",
  },
  [CountryFlagsEmojis.COLOMBIA_FLAG]: {
    name: "Columbia flag",
    unicode: "U+1F1E8 U+1F1F4",
    emoji: "🇨🇴",
  },
  [CountryFlagsEmojis.CLIPPERTON_ISLAND_FLAG]: {
    name: "Clipperton Island flag",
    unicode: "U+1F1E8 U+1F1F5",
    emoji: "🇨🇵",
  },
  [CountryFlagsEmojis.COSTA_RICA_FLAG]: {
    name: "Costa Rica flag",
    unicode: "U+1F1E8 U+1F1F7",
    emoji: "🇨🇷",
  },
  [CountryFlagsEmojis.CUBA_FLAG]: {
    name: "Cuba flag",
    unicode: "U+1F1E8 U+1F1FA",
    emoji: "🇨🇺",
  },
  [CountryFlagsEmojis.CAPE_VERDE_FLAG]: {
    name: "Cape Verde flag",
    unicode: "U+1F1E8 U+1F1FB",
    emoji: "🇨🇻",
  },
  [CountryFlagsEmojis.CURACAO_FLAG]: {
    name: "Curaçao flag",
    unicode: "U+1F1E8 U+1F1FC",
    emoji: "🇨🇼",
  },
  [CountryFlagsEmojis.CHRISTMAS_ISLAND_FLAG]: {
    name: "Christmas Island flag",
    unicode: "U+1F1E8 U+1F1FD",
    emoji: "🇨🇽",
  },
  [CountryFlagsEmojis.CYPRUS_FLAG]: {
    name: "Cyprus flag",
    unicode: "U+1F1E8 U+1F1FE",
    emoji: "🇨🇾",
  },
  [CountryFlagsEmojis.CZECH_REPUBLIC_FLAG]: {
    name: "Czech Republic flag",
    unicode: "U+1F1E8 U+1F1FF",
    emoji: "🇨🇿",
  },
  [CountryFlagsEmojis.GERMANY_FLAG]: {
    name: "Germany flag",
    unicode: "U+1F1E9 U+1F1EA",
    emoji: "🇩🇪",
  },
  [CountryFlagsEmojis.DIEGO_GARCIA_FLAG]: {
    name: "Diego Garcia flag",
    unicode: "U+1F1E9 U+1F1EC",
    emoji: "🇩🇬",
  },
  [CountryFlagsEmojis.DJIBOUTI_FLAG]: {
    name: "Djibouti flag",
    unicode: "U+1F1E9 U+1F1EF",
    emoji: "🇩🇯",
  },
  [CountryFlagsEmojis.DENMARK_FLAG]: {
    name: "Denmark flag",
    unicode: "U+1F1E9 U+1F1F0",
    emoji: "🇩🇰",
  },
  [CountryFlagsEmojis.DOMINICA_FLAG]: {
    name: "Dominica flag",
    unicode: "U+1F1E9 U+1F1F2",
    emoji: "🇩🇲",
  },
  [CountryFlagsEmojis.DOMINICAN_REPUBLIC_FLAG]: {
    name: "Dominican Republic flag",
    unicode: "U+1F1E9 U+1F1F4",
    emoji: "🇩🇴",
  },
  [CountryFlagsEmojis.CEUTA_MELILLA_FLAG]: {
    name: "Ceuta & Melilla flag",
    unicode: "U+1F1EA U+1F1E6",
    emoji: "🇪🇦",
  },
  [CountryFlagsEmojis.ECUADOR_FLAG]: {
    name: "Ecuador flag",
    unicode: "U+1F1EA U+1F1E8",
    emoji: "🇪🇨",
  },
  [CountryFlagsEmojis.ESTONIA_FLAG]: {
    name: "Estonia flag",
    unicode: "U+1F1EA U+1F1EA",
    emoji: "🇪🇪",
  },
  [CountryFlagsEmojis.EGYPT_FLAG]: {
    name: "Egypt flag",
    unicode: "U+1F1EA U+1F1EC",
    emoji: "🇪🇬",
  },
  [CountryFlagsEmojis.WESTERN_SAHARA_FLAG]: {
    name: "Western Sahara flag",
    unicode: "U+1F1EA U+1F1ED",
    emoji: "🇪🇭",
  },
  [CountryFlagsEmojis.ERITREA_FLAG]: {
    name: "Eritre flag",
    unicode: "U+1F1EA U+1F1F7",
    emoji: "🇪🇷",
  },
  [CountryFlagsEmojis.SPAIN_FLAG]: {
    name: "Spain flag",
    unicode: "U+1F1EA U+1F1F8",
    emoji: "🇪🇸",
  },
  [CountryFlagsEmojis.ETHIOPIA_FLAG]: {
    name: "Ethiopia flag",
    unicode: "U+1F1EA U+1F1F9",
    emoji: "🇪🇹",
  },
  [CountryFlagsEmojis.EUROPEAN_UNION_FLAG]: {
    name: "European Union flag",
    unicode: "U+1F1EA U+1F1FA",
    emoji: "🇪🇺",
  },
  [CountryFlagsEmojis.FINLAND_FLAG]: {
    name: "Finalnd flag",
    unicode: "U+1F1EB U+1F1EE",
    emoji: "🇫🇮",
  },
  [CountryFlagsEmojis.FIJI_FLAG]: {
    name: "Fiji Island flag",
    unicode: "U+1F1EB U+1F1EF",
    emoji: "🇫🇯",
  },
  [CountryFlagsEmojis.FALKLAND_ISLANDS_FLAG]: {
    name: "Falkland Islands flag",
    unicode: "U+1F1EB U+1F1F0",
    emoji: "🇫🇰",
  },
  [CountryFlagsEmojis.MICRONESIA_FLAG]: {
    name: "Micronesia flag",
    unicode: "U+1F1EB U+1F1F2",
    emoji: "🇫🇲",
  },
  [CountryFlagsEmojis.FAROE_ISLANDS_FLAG]: {
    name: "Faroe Islands flag",
    unicode: "U+1F1EB U+1F1F4",
    emoji: "🇫🇴",
  },
  [CountryFlagsEmojis.FRANCE_FLAG]: {
    name: "France flag",
    unicode: "U+1F1EB U+1F1F7",
    emoji: "🇫🇷",
  },
  [CountryFlagsEmojis.GABON_FLAG]: {
    name: "Gabon flag",
    unicode: "U+1F1EC U+1F1E6",
    emoji: "🇬🇦",
  },
  [CountryFlagsEmojis.UNITED_KINGDOM_FLAG]: {
    name: "United Kingdom flag",
    unicode: "U+1F1EC U+1F1E7",
    emoji: "🇬🇧",
  },
  [CountryFlagsEmojis.GRENADA_FLAG]: {
    name: "Grenada flag",
    unicode: "U+1F1EC U+1F1E9",
    emoji: "🇬🇩",
  },
  [CountryFlagsEmojis.GEORGIA_FLAG]: {
    name: "Georgia flag",
    unicode: "U+1F1EC U+1F1EA",
    emoji: "🇬🇪",
  },
  [CountryFlagsEmojis.FRENCH_GUIANA_FLAG]: {
    name: "French Guiana flag",
    unicode: "U+1F1EC U+1F1EB",
    emoji: "🇬🇫",
  },
  [CountryFlagsEmojis.GUERNSEY_FLAG]: {
    name: "Guernsey flag",
    unicode: "U+1F1EC U+1F1EC",
    emoji: "🇬🇬",
  },
  [CountryFlagsEmojis.GHANA_FLAG]: {
    name: "Ghana flag",
    unicode: "U+1F1EC U+1F1ED",
    emoji: "🇬🇭",
  },
  [CountryFlagsEmojis.GIBRALTAR_FLAG]: {
    name: "Gibraltar flag",
    unicode: "U+1F1EC U+1F1EE",
    emoji: "🇬🇮",
  },
  [CountryFlagsEmojis.GREENLAND_FLAG]: {
    name: "Greenland flag",
    unicode: "U+1F1EC U+1F1F1",
    emoji: "🇬🇱",
  },
  [CountryFlagsEmojis.GAMBIA_FLAG]: {
    name: "Gambia flag",
    unicode: "U+1F1EC U+1F1F2",
    emoji: "🇬🇲",
  },
  [CountryFlagsEmojis.GUINEA_FLAG]: {
    name: "Guinea flag",
    unicode: "U+1F1EC U+1F1F3",
    emoji: "🇬🇳",
  },
  [CountryFlagsEmojis.GUADELOUPE_FLAG]: {
    name: "Guadeloupe flag",
    unicode: "U+1F1EC U+1F1F5",
    emoji: "🇬🇵",
  },
  [CountryFlagsEmojis.EQUATORIAL_GUINEA_FLAG]: {
    name: "Equatorial Guinea flag",
    unicode: "U+1F1EC U+1F1F6",
    emoji: "🇬🇶",
  },
  [CountryFlagsEmojis.GREECE_FLAG]: {
    name: "Greece flag",
    unicode: "U+1F1EC U+1F1F7",
    emoji: "🇬🇷",
  },
  [CountryFlagsEmojis.SOUTH_GEORGIA_SANDWICH_ISLANDS_FLAG]: {
    name: "South Georgia & South Sandwich Islands flag",
    unicode: "U+1F1EC U+1F1F8",
    emoji: "🇬🇸",
  },
  [CountryFlagsEmojis.GUATEMALA_FLAG]: {
    name: "Guatemala flag",
    unicode: "U+1F1EC U+1F1F9",
    emoji: "🇬🇹",
  },
  [CountryFlagsEmojis.GUAM_FLAG]: {
    name: "Guam flag",
    unicode: "U+1F1EC U+1F1FA",
    emoji: "🇬🇺",
  },
  [CountryFlagsEmojis.GUINEA_BISSAU_FLAG]: {
    name: "Guinea Bissau flag",
    unicode: "U+1F1EC U+1F1FC",
    emoji: "🇬🇼",
  },
  [CountryFlagsEmojis.GUYANA_FLAG]: {
    name: "Guyana flag",
    unicode: "U+1F1EC U+1F1FE",
    emoji: "🇬🇾",
  },
  [CountryFlagsEmojis.HONG_KONG_FLAG]: {
    name: "Hong Kong SAR China flag",
    unicode: "U+1F1ED U+1F1F0",
    emoji: "🇭🇰",
  },
  [CountryFlagsEmojis.HEARD_MCDONALD_ISLANDS_FLAG]: {
    name: "Heard & McDonald Islands flag",
    unicode: "U+1F1ED U+1F1F2",
    emoji: "🇭🇲",
  },
  [CountryFlagsEmojis.HONDURAS_FLAG]: {
    name: "Honduras flag",
    unicode: "U+1F1ED U+1F1F3",
    emoji: "🇭🇳",
  },
  [CountryFlagsEmojis.CROATIA_FLAG]: {
    name: "Croatia flag",
    unicode: "U+1F1ED U+1F1F7",
    emoji: "🇭🇷",
  },
  [CountryFlagsEmojis.HAITI_FLAG]: {
    name: "Haiti flag",
    unicode: "U+1F1ED U+1F1F9",
    emoji: "🇭🇹",
  },
  [CountryFlagsEmojis.HUNGARY_FLAG]: {
    name: "Hungary flag",
    unicode: "U+1F1ED U+1F1FA",
    emoji: "🇭🇺",
  },
  [CountryFlagsEmojis.CANARY_ISLANDS_FLAG]: {
    name: "Canary Islands flag",
    unicode: "U+1F1EE U+1F1E8",
    emoji: "🇮🇨",
  },
  [CountryFlagsEmojis.INDONESIA_FLAG]: {
    name: "Indonesia flag",
    unicode: "U+1F1EE U+1F1E9",
    emoji: "🇮🇩",
  },
  [CountryFlagsEmojis.IRELAND_FLAG]: {
    name: "Ireland flag",
    unicode: "U+1F1EE U+1F1EA",
    emoji: "🇮🇪",
  },
  [CountryFlagsEmojis.ISRAEL_FLAG]: {
    name: "Israel flag",
    unicode: "U+1F1EE U+1F1F1",
    emoji: "🇮🇱",
  },
  [CountryFlagsEmojis.ISLE_OF_MAN_FLAG]: {
    name: "Isle of Man flag",
    unicode: "U+1F1EE U+1F1F2",
    emoji: "🇮🇲",
  },
  [CountryFlagsEmojis.INDIA_FLAG]: {
    name: "India flag",
    unicode: "U+1F1EE U+1F1F3",
    emoji: "🇮🇳",
  },
  [CountryFlagsEmojis.BRITISH_INDIAN_OCEAN_TERRITORY_FLAG]: {
    name: "British Indian Ocean Territory flag",
    unicode: "U+1F1EE U+1F1F4",
    emoji: "🇮🇴",
  },
  [CountryFlagsEmojis.IRAQ_FLAG]: {
    name: "Iraq flag",
    unicode: "U+1F1EE U+1F1F6",
    emoji: "🇮🇶",
  },
  [CountryFlagsEmojis.IRAN_FLAG]: {
    name: "Iran flag",
    unicode: "U+1F1EE U+1F1F7",
    emoji: "🇮🇷",
  },
  [CountryFlagsEmojis.ICELAND_FLAG]: {
    name: "Iceland flag",
    unicode: "U+1F1EE U+1F1F8",
    emoji: "🇮🇸",
  },
  [CountryFlagsEmojis.ITALY_FLAG]: {
    name: "Italy flag",
    unicode: "U+1F1EE U+1F1F9",
    emoji: "🇮🇹",
  },
  [CountryFlagsEmojis.JERSEY_FLAG]: {
    name: "Jersey flag",
    unicode: "U+1F1EF U+1F1EA",
    emoji: "🇯🇪",
  },
  [CountryFlagsEmojis.JAMAICA_FLAG]: {
    name: "Jamaica flag",
    unicode: "U+1F1EF U+1F1F2",
    emoji: "🇯🇲",
  },
  [CountryFlagsEmojis.JORDAN_FLAG]: {
    name: "Jordan flag",
    unicode: "U+1F1EF U+1F1F4",
    emoji: "🇯🇴",
  },
  [CountryFlagsEmojis.JAPAN_FLAG]: {
    name: "Japan flag",
    unicode: "U+1F1EF U+1F1F5",
    emoji: "🇯🇵",
  },
  [CountryFlagsEmojis.KENYA_FLAG]: {
    name: "Kenya flag",
    unicode: "U+1F1F0 U+1F1EA",
    emoji: "🇰🇪",
  },
  [CountryFlagsEmojis.KYRGYZSTAN_FLAG]: {
    name: "Kyrgyzstan flag",
    unicode: "U+1F1F0 U+1F1EC",
    emoji: "🇰🇬",
  },
  [CountryFlagsEmojis.CAMBODIA_FLAG]: {
    name: "Cambodia flag",
    unicode: "U+1F1F0 U+1F1ED",
    emoji: "🇰🇭",
  },
  [CountryFlagsEmojis.KIRIBATI_FLAG]: {
    name: "Kiribati flag",
    unicode: "U+1F1F0 U+1F1EE",
    emoji: "🇰🇮",
  },
  [CountryFlagsEmojis.COMOROS_FLAG]: {
    name: "Comoros flag",
    unicode: "U+1F1F0 U+1F1F2",
    emoji: "🇰🇲",
  },
  [CountryFlagsEmojis.ST_KITTS_NEVIS_FLAG]: {
    name: "St. Kitts & Nevis flag",
    unicode: "U+1F1F0 U+1F1F3",
    emoji: "🇰🇳",
  },
  [CountryFlagsEmojis.NORTH_KOREA_FLAG]: {
    name: "North Korea flag",
    unicode: "U+1F1F0 U+1F1F5",
    emoji: "🇰🇵",
  },
  [CountryFlagsEmojis.SOUTH_KOREA_FLAG]: {
    name: "South Korea flag",
    unicode: "U+1F1F0 U+1F1F7",
    emoji: "🇰🇷",
  },
  [CountryFlagsEmojis.KUWAIT_FLAG]: {
    name: "Kuwait flag",
    unicode: "U+1F1F0 U+1F1FC",
    emoji: "🇰🇼",
  },
  [CountryFlagsEmojis.CAYMAN_ISLANDS_FLAG]: {
    name: "Cayman Islands flag",
    unicode: "U+1F1F0 U+1F1FE",
    emoji: "🇰🇾",
  },
  [CountryFlagsEmojis.KAZAKHSTAN_FLAG]: {
    name: "Kazakhstan flag",
    unicode: "U+1F1F0 U+1F1FF",
    emoji: "🇰🇿",
  },
  [CountryFlagsEmojis.LAOS_FLAG]: {
    name: "Laos flag",
    unicode: "U+1F1F1 U+1F1E6",
    emoji: "🇱🇦",
  },
  [CountryFlagsEmojis.LEBANON_FLAG]: {
    name: "Lebanon flag",
    unicode: "U+1F1F1 U+1F1E7",
    emoji: "🇱🇧",
  },
  [CountryFlagsEmojis.ST_LUCIA_FLAG]: {
    name: "St. Lucia flag",
    unicode: "U+1F1F1 U+1F1E8",
    emoji: "🇱🇨",
  },
  [CountryFlagsEmojis.LIECHTENSTEIN_FLAG]: {
    name: "Liechtenstein flag",
    unicode: "U+1F1F1 U+1F1EE",
    emoji: "🇱🇮",
  },
  [CountryFlagsEmojis.SRI_LANKA_FLAG]: {
    name: "Sri Lanka flag",
    unicode: "U+1F1F1 U+1F1F0",
    emoji: "🇱🇰",
  },
  [CountryFlagsEmojis.LIBERIA_FLAG]: {
    name: "Liberia flag",
    unicode: "U+1F1F1 U+1F1F7",
    emoji: "🇱🇷",
  },
  [CountryFlagsEmojis.LESOTHO_FLAG]: {
    name: "Lesotho flag",
    unicode: "U+1F1F1 U+1F1F8",
    emoji: "🇱🇸",
  },
  [CountryFlagsEmojis.LITHUANIA_FLAG]: {
    name: "Lithuania flag",
    unicode: "U+1F1F1 U+1F1F9",
    emoji: "🇱🇹",
  },
  [CountryFlagsEmojis.LUXEMBOURG_FLAG]: {
    name: "Luxembourg flag",
    unicode: "U+1F1F1 U+1F1FA",
    emoji: "🇱🇺",
  },
  [CountryFlagsEmojis.LATVIA_FLAG]: {
    name: "Latvia flag",
    unicode: "U+1F1F1 U+1F1FB",
    emoji: "🇱🇻",
  },
  [CountryFlagsEmojis.LIBYA_FLAG]: {
    name: "Libya flag",
    unicode: "U+1F1F1 U+1F1FE",
    emoji: "🇱🇾",
  },
  [CountryFlagsEmojis.MOROCCO_FLAG]: {
    name: "Morocco flag",
    unicode: "U+1F1F2 U+1F1E6",
    emoji: "🇲🇦",
  },
  [CountryFlagsEmojis.MONACO_FLAG]: {
    name: "Monaco flag",
    unicode: "U+1F1F2 U+1F1E8",
    emoji: "🇲🇨",
  },
  [CountryFlagsEmojis.MOLDOVA_FLAG]: {
    name: "Moldova flag",
    unicode: "U+1F1F2 U+1F1E9",
    emoji: "🇲🇩",
  },
  [CountryFlagsEmojis.MONTENEGRO_FLAG]: {
    name: "Montenegro flag",
    unicode: "U+1F1F2 U+1F1EA",
    emoji: "🇲🇪",
  },
  [CountryFlagsEmojis.ST_MARTIN_FLAG]: {
    name: "St. Martin flag",
    unicode: "U+1F1F2 U+1F1EB",
    emoji: "🇲🇫",
  },
  [CountryFlagsEmojis.MADAGASCAR_FLAG]: {
    name: "Madagascar flag",
    unicode: "U+1F1F2 U+1F1EC",
    emoji: "🇲🇬",
  },
  [CountryFlagsEmojis.MARSHALL_ISLANDS_FLAG]: {
    name: "Marshall Islands flag",
    unicode: "U+1F1F2 U+1F1ED",
    emoji: "🇲🇭",
  },
  [CountryFlagsEmojis.NORTH_MACEDONIA_FLAG]: {
    name: "North Macedonia flag",
    unicode: "U+1F1F2 U+1F1F0",
    emoji: "🇲🇰",
  },
  [CountryFlagsEmojis.MALI_FLAG]: {
    name: "Mali flag",
    unicode: "U+1F1F2 U+1F1F1",
    emoji: "🇲🇱",
  },
  [CountryFlagsEmojis.MYANMAR_FLAG]: {
    name: "Myanmar flag",
    unicode: "U+1F1F2 U+1F1F2",
    emoji: "🇲🇲",
  },
  [CountryFlagsEmojis.MONGOLIA_FLAG]: {
    name: "Mongolia flag",
    unicode: "U+1F1F2 U+1F1F3",
    emoji: "🇲🇳",
  },
  [CountryFlagsEmojis.MACAO_FLAG]: {
    name: "Macao SAR China flag",
    unicode: "U+1F1F2 U+1F1F4",
    emoji: "🇲🇴",
  },
  [CountryFlagsEmojis.NORTHERN_MARIANA_ISLANDS_FLAG]: {
    name: "Northern Mariana Islands flag",
    unicode: "U+1F1F2 U+1F1F5",
    emoji: "🇲🇵",
  },
  [CountryFlagsEmojis.MARTINIQUE_FLAG]: {
    name: "Martinique flag",
    unicode: "U+1F1F2 U+1F1F6",
    emoji: "🇲🇶",
  },
  [CountryFlagsEmojis.MAURITANIA_FLAG]: {
    name: "Mauritania flag",
    unicode: "U+1F1F2 U+1F1F7",
    emoji: "🇲🇷",
  },
  [CountryFlagsEmojis.MONTSERRAT_FLAG]: {
    name: "Montserrat flag",
    unicode: "U+1F1F2 U+1F1F8",
    emoji: "🇲🇸",
  },
  [CountryFlagsEmojis.MALTA_FLAG]: {
    name: "Malta flag",
    unicode: "U+1F1F2 U+1F1F9",
    emoji: "🇲🇹",
  },
  [CountryFlagsEmojis.MAURITIUS_FLAG]: {
    name: "Mauritius flag",
    unicode: "U+1F1F2 U+1F1FA",
    emoji: "🇲🇺",
  },
  [CountryFlagsEmojis.MALDIVES_FLAG]: {
    name: "Maldives flag",
    unicode: "U+1F1F2 U+1F1FB",
    emoji: "🇲🇻",
  },
  [CountryFlagsEmojis.MALAWI_FLAG]: {
    name: "Malawi flag",
    unicode: "U+1F1F2 U+1F1FC",
    emoji: "🇲🇼",
  },
  [CountryFlagsEmojis.MEXICO_FLAG]: {
    name: "Mexico flag",
    unicode: "U+1F1F2 U+1F1FD",
    emoji: "🇲🇽",
  },
  [CountryFlagsEmojis.MALAYSIA_FLAG]: {
    name: "Malaysia flag",
    unicode: "U+1F1F2 U+1F1FE",
    emoji: "🇲🇾",
  },
  [CountryFlagsEmojis.MOZAMBIQUE_FLAG]: {
    name: "Mozambique flag",
    unicode: "U+1F1F2 U+1F1FF",
    emoji: "🇲🇿",
  },
  [CountryFlagsEmojis.NAMIBIA_FLAG]: {
    name: "Namibia flag",
    unicode: "U+1F1F3 U+1F1E6",
    emoji: "🇳🇦",
  },
  [CountryFlagsEmojis.NEW_CALEDONIA_FLAG]: {
    name: "New Caledonia flag",
    unicode: "U+1F1F3 U+1F1E8",
    emoji: "🇳🇨",
  },
  [CountryFlagsEmojis.NIGER_FLAG]: {
    name: "Niger Republic flag",
    unicode: "U+1F1F3 U+1F1EA",
    emoji: "🇳🇪",
  },
  [CountryFlagsEmojis.NIGERIA_FLAG]: {
    name: "Nigeria flag",
    unicode: "U+1F1F3 U+1F1EC",
    emoji: "🇳🇬",
  },
  [CountryFlagsEmojis.NORFOLK_ISLAND_FLAG]: {
    name: "Norfolk Island flag",
    unicode: "U+1F1F3 U+1F1EB",
    emoji: "🇳🇫",
  },
  [CountryFlagsEmojis.NICARAGUA_FLAG]: {
    name: "Nicaragua flag",
    unicode: "U+1F1F3 U+1F1EE",
    emoji: "🇳🇮",
  },
  [CountryFlagsEmojis.NETHERLANDS_FLAG]: {
    name: "Netherlands flag",
    unicode: "U+1F1F3 U+1F1F1",
    emoji: "🇳🇱",
  },
  [CountryFlagsEmojis.NORWAY_FLAG]: {
    name: "Norway flag",
    unicode: "U+1F1F3 U+1F1F4",
    emoji: "🇳🇴",
  },
  [CountryFlagsEmojis.NEPAL_FLAG]: {
    name: "Nepal flag",
    unicode: "U+1F1F3 U+1F1F5",
    emoji: "🇳🇵",
  },
  [CountryFlagsEmojis.NAURU_FLAG]: {
    name: "Nauru flag",
    unicode: "U+1F1F3 U+1F1F7",
    emoji: "🇳🇷",
  },
  [CountryFlagsEmojis.NIUE_FLAG]: {
    name: "Niue flag",
    unicode: "U+1F1F3 U+1F1FA",
    emoji: "🇳🇺",
  },
  [CountryFlagsEmojis.NEW_ZEALAND_FLAG]: {
    name: "New Zealand flag",
    unicode: "U+1F1F3 U+1F1FF",
    emoji: "🇳🇿",
  },
  [CountryFlagsEmojis.OMAN_FLAG]: {
    name: "Oman flag",
    unicode: "U+1F1F4 U+1F1F2",
    emoji: "🇴🇲",
  },
  [CountryFlagsEmojis.PANAMA_FLAG]: {
    name: "Panama flag",
    unicode: "U+1F1F5 U+1F1E6",
    emoji: "🇵🇦",
  },
  [CountryFlagsEmojis.PERU_FLAG]: {
    name: "Peru flag",
    unicode: "U+1F1F5 U+1F1EA",
    emoji: "🇵🇪",
  },
  [CountryFlagsEmojis.FRENCH_POLYNESIA_FLAG]: {
    name: "French Polynesia flag",
    unicode: "U+1F1F5 U+1F1EB",
    emoji: "🇵🇫",
  },
  [CountryFlagsEmojis.PAPUA_NEW_GUINEA_FLAG]: {
    name: "Papua New Guinea flag",
    unicode: "U+1F1F5 U+1F1EC",
    emoji: "🇵🇬",
  },
  [CountryFlagsEmojis.PHILIPPINES_FLAG]: {
    name: "Philippines flag",
    unicode: "U+1F1F5 U+1F1ED",
    emoji: "🇵🇭",
  },
  [CountryFlagsEmojis.PAKISTAN_FLAG]: {
    name: "Pakistan flag",
    unicode: "U+1F1F5 U+1F1F0",
    emoji: "🇵🇰",
  },
  [CountryFlagsEmojis.POLAND_FLAG]: {
    name: "Poland flag",
    unicode: "U+1F1F5 U+1F1F1",
    emoji: "🇵🇱",
  },
  [CountryFlagsEmojis.ST_PIERRE_MIQUELON_FLAG]: {
    name: "St. Pierre & Miquelon flag",
    unicode: "U+1F1F5 U+1F1F2",
    emoji: "🇵🇲",
  },
  [CountryFlagsEmojis.PITCAIRN_ISLANDS_FLAG]: {
    name: "Pitcairn Islands flag",
    unicode: "U+1F1F5 U+1F1F3",
    emoji: "🇵🇳",
  },
  [CountryFlagsEmojis.PUERTO_RICO_FLAG]: {
    name: "Puerto Rico flag",
    unicode: "U+1F1F5 U+1F1F7",
    emoji: "🇵🇷",
  },
  [CountryFlagsEmojis.PALESTINIAN_TERRITORIES_FLAG]: {
    name: "Palestinian Territories flag",
    unicode: "U+1F1F5 U+1F1F8",
    emoji: "🇵🇸",
  },
  [CountryFlagsEmojis.PORTUGAL_FLAG]: {
    name: "Portugal flag",
    unicode: "U+1F1F5 U+1F1F9",
    emoji: "🇵🇹",
  },
  [CountryFlagsEmojis.PALAU_FLAG]: {
    name: "Palau flag",
    unicode: "U+1F1F5 U+1F1FC",
    emoji: "🇵🇼",
  },
  [CountryFlagsEmojis.PARAGUAY_FLAG]: {
    name: "Paraguay flag",
    unicode: "U+1F1F5 U+1F1FE",
    emoji: "🇵🇾",
  },
  [CountryFlagsEmojis.QATAR_FLAG]: {
    name: "Qatar flag",
    unicode: "U+1F1F6 U+1F1E6",
    emoji: "🇶🇦",
  },
  [CountryFlagsEmojis.REUNION_FLAG]: {
    name: "Réunion flag",
    unicode: "U+1F1F7 U+1F1EA",
    emoji: "🇷🇪",
  },
  [CountryFlagsEmojis.ROMANIA_FLAG]: {
    name: "Romania flag",
    unicode: "U+1F1F7 U+1F1F4",
    emoji: "🇷🇴",
  },
  [CountryFlagsEmojis.SERBIA_FLAG]: {
    name: "Serbia flag",
    unicode: "U+1F1F7 U+1F1F8",
    emoji: "🇷🇸",
  },
  [CountryFlagsEmojis.RUSSIA_FLAG]: {
    name: "Russia flag",
    unicode: "U+1F1F7 U+1F1FA",
    emoji: "🇷🇺",
  },
  [CountryFlagsEmojis.RWANDA_FLAG]: {
    name: "Rwanda flag",
    unicode: "U+1F1F7 U+1F1FC",
    emoji: "🇷🇼",
  },
  [CountryFlagsEmojis.SAUDI_ARABIA_FLAG]: {
    name: "Saudi Arabia flag",
    unicode: "U+1F1F8 U+1F1E6",
    emoji: "🇸🇦",
  },
  [CountryFlagsEmojis.SOLOMON_ISLANDS_FLAG]: {
    name: "Solomon Islands flag",
    unicode: "U+1F1F8 U+1F1E7",
    emoji: "🇸🇧",
  },
  [CountryFlagsEmojis.SEYCHELLES_FLAG]: {
    name: "Seychelles flag",
    unicode: "U+1F1F8 U+1F1E8",
    emoji: "🇸🇨",
  },
  [CountryFlagsEmojis.SUDAN_FLAG]: {
    name: "Sudan flag",
    unicode: "U+1F1F8 U+1F1E9",
    emoji: "🇸🇩",
  },
  [CountryFlagsEmojis.SWEDEN_FLAG]: {
    name: "Sweden flag",
    unicode: "U+1F1F8 U+1F1EA",
    emoji: "🇸🇪",
  },
  [CountryFlagsEmojis.SINGAPORE_FLAG]: {
    name: "Singapore flag",
    unicode: "U+1F1F8 U+1F1EC",
    emoji: "🇸🇬",
  },
  [CountryFlagsEmojis.ST_HELENA_FLAG]: {
    name: "St. Helena flag",
    unicode: "U+1F1F8 U+1F1ED",
    emoji: "🇸🇭",
  },
  [CountryFlagsEmojis.SLOVENIA_FLAG]: {
    name: "Slovenia flag",
    unicode: "U+1F1F8 U+1F1EE",
    emoji: "🇸🇮",
  },
  [CountryFlagsEmojis.SVALBARD_JAN_MAYEN_FLAG]: {
    name: "Svalbard & Jan Mayen flag",
    unicode: "U+1F1F8 U+1F1EF",
    emoji: "🇸🇯",
  },
  [CountryFlagsEmojis.SLOVAKIA_FLAG]: {
    name: "Slovakia flag",
    unicode: "U+1F1F8 U+1F1F0",
    emoji: "🇸🇰",
  },
  [CountryFlagsEmojis.SIERRA_LEONE_FLAG]: {
    name: "Sierra Leone flag",
    unicode: "U+1F1F8 U+1F1F1",
    emoji: "🇸🇱",
  },
  [CountryFlagsEmojis.SAN_MARINO_FLAG]: {
    name: "San Marino flag",
    unicode: "U+1F1F8 U+1F1F2",
    emoji: "🇸🇲",
  },
  [CountryFlagsEmojis.SENEGAL_FLAG]: {
    name: "Senegal flag",
    unicode: "U+1F1F8 U+1F1F3",
    emoji: "🇸🇳",
  },
  [CountryFlagsEmojis.SOMALIA_FLAG]: {
    name: "Somalia flag",
    unicode: "U+1F1F8 U+1F1F4",
    emoji: "🇸🇴",
  },
  [CountryFlagsEmojis.SURINAME_FLAG]: {
    name: "Suriname flag",
    unicode: "U+1F1F8 U+1F1F7",
    emoji: "🇸🇷",
  },
  [CountryFlagsEmojis.SOUTH_SUDAN_FLAG]: {
    name: "South Sudan flag",
    unicode: "U+1F1F8 U+1F1F8",
    emoji: "🇸🇸",
  },
  [CountryFlagsEmojis.SAO_TOME_PRINCIPE_FLAG]: {
    name: "São Tomé & Príncipe flag",
    unicode: "U+1F1F8 U+1F1F9",
    emoji: "🇸🇹",
  },
  [CountryFlagsEmojis.EL_SALVADOR_FLAG]: {
    name: "El Salvador flag",
    unicode: "U+1F1F8 U+1F1FB",
    emoji: "🇸🇻",
  },
  [CountryFlagsEmojis.SAINT_MAARTEN_FLAG]: {
    name: "Saint Maarten flag",
    unicode: "U+1F1F8 U+1F1FD",
    emoji: "🇸🇽",
  },
  [CountryFlagsEmojis.SYRIA_FLAG]: {
    name: "Syria flag",
    unicode: "U+1F1F8 U+1F1FE",
    emoji: "🇸🇾",
  },
  [CountryFlagsEmojis.ESWATINI_FLAG]: {
    name: "Eswatini flag",
    unicode: "U+1F1F8 U+1F1FF",
    emoji: "🇸🇿",
  },
  [CountryFlagsEmojis.TRISTAN_DA_CUNHA_FLAG]: {
    name: "Tristan da Cunha flag",
    unicode: "U+1F1F9 U+1F1E6",
    emoji: "🇹🇦",
  },
  [CountryFlagsEmojis.TURKS_CAICOS_ISLANDS_FLAG]: {
    name: "Turks & Caicos Islands flag",
    unicode: "U+1F1F9 U+1F1E8",
    emoji: "🇹🇨",
  },
  [CountryFlagsEmojis.CHAD_FLAG]: {
    name: "Chad flag",
    unicode: "U+1F1F9 U+1F1E9",
    emoji: "🇹🇩",
  },
  [CountryFlagsEmojis.FRENCH_SOUTHERN_TERRITORIES_FLAG]: {
    name: "French Southern Territories flag",
    unicode: "U+1F1F9 U+1F1EB",
    emoji: "🇹🇫",
  },
  [CountryFlagsEmojis.TOGO_FLAG]: {
    name: "Togo flag",
    unicode: "U+1F1F9 U+1F1EC",
    emoji: "🇹🇬",
  },
  [CountryFlagsEmojis.THAILAND_FLAG]: {
    name: "Thailand flag",
    unicode: "U+1F1F9 U+1F1ED",
    emoji: "🇹🇭",
  },
  [CountryFlagsEmojis.TAJIKISTAN_FLAG]: {
    name: "Tajikistan flag",
    unicode: "U+1F1F9 U+1F1EF",
    emoji: "🇹🇯",
  },
  [CountryFlagsEmojis.TOKELAU_FLAG]: {
    name: "Tokelau flag",
    unicode: "U+1F1F9 U+1F1F0",
    emoji: "🇹🇰",
  },
  [CountryFlagsEmojis.TIMOR_LESTE_FLAG]: {
    name: "Timor-Leste flag",
    unicode: "U+1F1F9 U+1F1F1",
    emoji: "🇹🇱",
  },
  [CountryFlagsEmojis.TURKMENISTAN_FLAG]: {
    name: "Turkmenistan flag",
    unicode: "U+1F1F9 U+1F1F2",
    emoji: "🇹🇲",
  },
  [CountryFlagsEmojis.TUNISIA_FLAG]: {
    name: "Tunisia flag",
    unicode: "U+1F1F9 U+1F1F3",
    emoji: "🇹🇳",
  },
  [CountryFlagsEmojis.TONGA_FLAG]: {
    name: "Tonga flag",
    unicode: "U+1F1F9 U+1F1F4",
    emoji: "🇹🇴",
  },
  [CountryFlagsEmojis.TURKEY_FLAG]: {
    name: "Turkey flag",
    unicode: "U+1F1F9 U+1F1F7",
    emoji: "🇹🇷",
  },
  [CountryFlagsEmojis.TRINIDAD_TOBAGO_FLAG]: {
    name: "Trinidad & Tobago flag",
    unicode: "U+1F1F9 U+1F1F9",
    emoji: "🇹🇹",
  },
  [CountryFlagsEmojis.TUVALU_FLAG]: {
    name: "Tuvalu flag",
    unicode: "U+1F1F9 U+1F1FB",
    emoji: "🇹🇻",
  },
  [CountryFlagsEmojis.TAIWAN_FLAG]: {
    name: "Taiwan flag",
    unicode: "U+1F1F9 U+1F1FC",
    emoji: "🇹🇼",
  },
  [CountryFlagsEmojis.TANZANIA_FLAG]: {
    name: "Tanzania flag",
    unicode: "U+1F1F9 U+1F1FF",
    emoji: "🇹🇿",
  },
  [CountryFlagsEmojis.UKRAINE_FLAG]: {
    name: "Ukraine flag",
    unicode: "U+1F1FA U+1F1E6",
    emoji: "🇺🇦",
  },
  [CountryFlagsEmojis.UGANDA_FLAG]: {
    name: "Uganda flag",
    unicode: "U+1F1FA U+1F1EC",
    emoji: "🇺🇬",
  },
  [CountryFlagsEmojis.US_OUTLYING_ISLANDS_FLAG]: {
    name: "U.S. Outlying Islands flag",
    unicode: "U+1F1FA U+1F1F2",
    emoji: "🇺🇲",
  },
  [CountryFlagsEmojis.UNITED_NATIONS_FLAG]: {
    name: "United Nations flag",
    unicode: "U+1F1FA U+1F1F3",
    emoji: "🇺🇳",
  },
  [CountryFlagsEmojis.UNITED_STATES_FLAG]: {
    name: "United States flag",
    unicode: "U+1F1FA U+1F1F8",
    emoji: "🇺🇸",
  },
  [CountryFlagsEmojis.URUGUAY_FLAG]: {
    name: "Uruguay flag",
    unicode: "U+1F1FA U+1F1FE",
    emoji: "🇺🇾",
  },
  [CountryFlagsEmojis.UZBEKISTAN_FLAG]: {
    name: "Uzbekistan flag",
    unicode: "U+1F1FA U+1F1FF",
    emoji: "🇺🇿",
  },
  [CountryFlagsEmojis.VATICAN_CITY_FLAG]: {
    name: "Vatican City flag",
    unicode: "U+1F1FB U+1F1E6",
    emoji: "🇻🇦",
  },
  [CountryFlagsEmojis.ST_VINCENT_GRENADINES_FLAG]: {
    name: "St. Vincent & Grenadines flag",
    unicode: "U+1F1FB U+1F1E8",
    emoji: "🇻🇨",
  },
  [CountryFlagsEmojis.VENEZUELA_FLAG]: {
    name: "Venezuela flag",
    unicode: "U+1F1FB U+1F1EA",
    emoji: "🇻🇪",
  },
  [CountryFlagsEmojis.BRITISH_VIRGIN_ISLANDS_FLAG]: {
    name: "British Virgin Islands flag",
    unicode: "U+1F1FB U+1F1EC",
    emoji: "🇻🇬",
  },
  [CountryFlagsEmojis.US_VIRGIN_ISLANDS_FLAG]: {
    name: "U.S. Virgin Islands flag",
    unicode: "U+1F1FB U+1F1EE",
    emoji: "🇻🇮",
  },
  [CountryFlagsEmojis.VIETNAM_FLAG]: {
    name: "Vietnam flag",
    unicode: "U+1F1FB U+1F1F3",
    emoji: "🇻🇳",
  },
  [CountryFlagsEmojis.VANUATU_FLAG]: {
    name: "Vanuatu flag",
    unicode: "U+1F1FB U+1F1FA",
    emoji: "🇻🇺",
  },
  [CountryFlagsEmojis.WALLIS_FUTUNA_FLAG]: {
    name: "Wallis & Futuna flag",
    unicode: "U+1F1FC U+1F1EB",
    emoji: "🇼🇫",
  },
  [CountryFlagsEmojis.SAMOA_FLAG]: {
    name: "Samoa flag",
    unicode: "U+1F1FC U+1F1F8",
    emoji: "🇼🇸",
  },
  [CountryFlagsEmojis.KOSOVO_FLAG]: {
    name: "Kosovo flag",
    unicode: "U+1F1FD U+1F1F0",
    emoji: "🇽🇰",
  },
  [CountryFlagsEmojis.YEMEN_FLAG]: {
    name: "Yemen flag",
    unicode: "U+1F1FE U+1F1EA",
    emoji: "🇾🇪",
  },
  [CountryFlagsEmojis.MAYOTTE_FLAG]: {
    name: "Mayotte flag",
    unicode: "U+1F1FE U+1F1F9",
    emoji: "🇾🇹",
  },
  [CountryFlagsEmojis.SOUTH_AFRICA_FLAG]: {
    name: "South Africa flag",
    unicode: "U+1F1FF U+1F1E6",
    emoji: "🇿🇦",
  },
  [CountryFlagsEmojis.ZAMBIA_FLAG]: {
    name: "Zambia flag",
    unicode: "U+1F1FF U+1F1F2",
    emoji: "🇿🇲",
  },
  [CountryFlagsEmojis.ZIMBABWE_FLAG]: {
    name: "Zimbabwe flag",
    unicode: "U+1F1FF U+1F1FC",
    emoji: "🇿🇼",
  },
  [CountryFlagsEmojis.ENGLAND_FLAG]: {
    name: "England flag",
    unicode:
      "U+1F3F4 U+E0067 U+E0062 U+E0065 U+E006E U+E0067 U+E007F",
    emoji: "🏴",
  },
  [CountryFlagsEmojis.SCOTLAND_FLAG]: {
    name: "Scotland flag",
    unicode:
      "U+1F3F4 U+E0067 U+E0062 U+E0073 U+E0063 U+E0074 U+E007F",
    emoji: "🏴",
  },
  [CountryFlagsEmojis.WALES_FLAG]: {
    name: "Wales flag",
    unicode:
      "U+1F3F4 U+E0067 U+E0062 U+E0077 U+E006C U+E0073 U+E007F",
    emoji: "🏴",
  }
}