import { type EmojiDefinition } from "./types";

export enum FamilyEmojis {
  FAMILY = "family",
  FAMILY_MAN_WOMAN_BOY = "family_man_woman_boy",
  FAMILY_MAN_WOMAN_GIRL = "family_man_woman_girl",
  FAMILY_MAN_WOMAN_GIRL_BOY = "family_man_woman_girl_boy",
  FAMILY_MAN_WOMAN_BOY_BOY = "family_man_woman_boy_boy",
  FAMILY_MAN_WOMAN_GIRL_GIRL = "family_man_woman_girl_girl",
  FAMILY_MAN_MAN_BOY = "family_man_man_boy",
  FAMILY_MAN_MAN_GIRL = "family_man_man_girl",
  FAMILY_MAN_MAN_GIRL_BOY = "family_man_man_girl_boy",
  FAMILY_MAN_MAN_BOY_BOY = "family_man_man_boy_boy",
  FAMILY_MAN_MAN_GIRL_GIRL = "family_man_man_girl_girl",
  FAMILY_WOMAN_WOMAN_BOY = "family_woman_woman_boy",
  FAMILY_WOMAN_WOMAN_GIRL = "family_woman_woman_girl",
  FAMILY_WOMAN_WOMAN_GIRL_BOY = "family_woman_woman_girl_boy",
  FAMILY_WOMAN_WOMAN_BOY_BOY = "family_woman_woman_boy_boy",
  FAMILY_WOMAN_WOMAN_GIRL_GIRL = "family_woman_woman_girl_girl",
  FAMILY_MAN_BOY = "family_man_boy",
  FAMILY_MAN_BOY_BOY = "family_man_boy_boy",
  FAMILY_MAN_GIRL = "family_man_girl",
  FAMILY_MAN_GIRL_BOY = "family_man_girl_boy",
  FAMILY_MAN_GIRL_GIRL = "family_man_girl_girl",
  FAMILY_WOMAN_BOY = "family_woman_boy",
  FAMILY_WOMAN_BOY_BOY = "family_woman_boy_boy",
  FAMILY_WOMAN_GIRL = "family_woman_girl",
  FAMILY_WOMAN_GIRL_BOY = "family_woman_girl_boy",
  FAMILY_WOMAN_GIRL_GIRL = "family_woman_girl_girl",
  PEOPLE_HOLDING_HANDS = "people_holding_hands",
  WOMEN_HOLDING_HANDS = "women_holding_hands",
  WOMAN_AND_MAN_HOLDING_HANDS = "woman_and_man_holding_hands",
  MEN_HOLDING_HANDS = "men_holding_hands",
  KISS = "kiss",
  WOMAN_MAN_KISSING = "woman_man_kissing",
  MAN_MAN_KISSING = "man_man_kissing",
  WOMAN_WOMAN_KISSING = "woman_woman_kissing",
  WOMAN_MAN_COUPLE = "woman_man_couple",
  MAN_MAN_COUPLE = "man_man_couple",
  WOMAN_WOMAN_COUPLE = "woman_woman_couple",
  COUPLE_WITH_HEART = "couple_with_heart",
  PERSON_SPEAKING = "person_speaking",
  BUST_IN_SILHOUHETTE = "bust_in_silhouhette",
  BUSTS_IN_SILHOUETTE = "busts_in_silhouette",
  PEOPLE_HUGGING = "people_hugging",
}

export const familyEmojis: Record<FamilyEmojis, EmojiDefinition> = {
  [FamilyEmojis.FAMILY]: { name: "Family", unicode: "U+1F46A", emoji: "👪" },
  [FamilyEmojis.FAMILY_MAN_WOMAN_BOY]: { name: "Family of man, woman and boy", unicode: "U+1F468 U+200D U+1F469 U+200D U+1F466", emoji: "👨‍👩‍👦" },
  [FamilyEmojis.FAMILY_MAN_WOMAN_GIRL]: { name: "Family of man, woman and girl", unicode: "U+1F468 U+200D U+1F469 U+200D U+1F467", emoji: "👨‍👩‍👧" },
  [FamilyEmojis.FAMILY_MAN_WOMAN_GIRL_BOY]: { name: "Family of man, woman, boy, and girl", unicode: "U+1F468 U+200D U+1F469 U+200D U+1F467 U+200D U+1F466", emoji: "👨‍👩‍👧‍👦" },
  [FamilyEmojis.FAMILY_MAN_WOMAN_BOY_BOY]: { name: "Family of man, woman, boy, and boy", unicode: "U+1F468 U+200D U+1F469 U+200D U+1F466 U+200D U+1F466", emoji: "👨‍👩‍👦‍👦" },
  [FamilyEmojis.FAMILY_MAN_WOMAN_GIRL_GIRL]: { name: "Family of man, woman, girl, and girl", unicode: "U+1F468 U+200D U+1F469 U+200D U+1F467 U+200D U+1F467", emoji: "👨‍👩‍👧‍👧" },
  [FamilyEmojis.FAMILY_MAN_MAN_BOY]: { name: "Family of man, man, and boy", unicode: "U+1F468 U+200D U+1F468 U+200D U+1F466", emoji: "👨‍👨‍👦" },
  [FamilyEmojis.FAMILY_MAN_MAN_GIRL]: { name: "Family of man, man, and girl", unicode: "U+1F468 U+200D U+1F468 U+200D U+1F467", emoji: "👨‍👨‍👧" },
  [FamilyEmojis.FAMILY_MAN_MAN_GIRL_BOY]: { name: "Family of man, man, girl, and boy", unicode: "U+1F468 U+200D U+1F468 U+200D U+1F467 U+200D U+1F466", emoji: "👨‍👨‍👧‍👦" },
  [FamilyEmojis.FAMILY_MAN_MAN_BOY_BOY]: { name: "Family of man, man, boy, and boy", unicode: "U+1F468 U+200D U+1F468 U+200D U+1F466 U+200D U+1F466", emoji: "👨‍👨‍👦‍👦" },
  [FamilyEmojis.FAMILY_MAN_MAN_GIRL_GIRL]: { name: "Family of man, man, girl, and girl", unicode: "U+1F468 U+200D U+1F468 U+200D U+1F467 U+200D U+1F467", emoji: "👨‍👨‍👧‍👧" },
  [FamilyEmojis.FAMILY_WOMAN_WOMAN_BOY]: { name: "Family of woman, woman, and boy", unicode: "U+1F469 U+200D U+1F469 U+200D U+1F466", emoji: "👩‍👩‍👦" },
  [FamilyEmojis.FAMILY_WOMAN_WOMAN_GIRL]: { name: "Family of woman, woman, and girl", unicode: "U+1F469 U+200D U+1F469 U+200D U+1F467", emoji: "👩‍👩‍👧" },
  [FamilyEmojis.FAMILY_WOMAN_WOMAN_GIRL_BOY]: { name: "Family of woman, woman, girl, and boy", unicode: "U+1F469 U+200D U+1F469 U+200D U+1F467 U+200D U+1F466", emoji: "👩‍👩‍👧‍👦" },
  [FamilyEmojis.FAMILY_WOMAN_WOMAN_BOY_BOY]: { name: "Family of woman, woman, boy, and boy", unicode: "U+1F469 U+200D U+1F469 U+200D U+1F466 U+200D U+1F466", emoji: "👩‍👩‍👦‍👦" },
  [FamilyEmojis.FAMILY_WOMAN_WOMAN_GIRL_GIRL]: { name: "Family of woman, woman, girl, and girl", unicode: "U+1F469 U+200D U+1F469 U+200D U+1F467 U+200D U+1F467", emoji: "👩‍👩‍👧‍👧" },
  [FamilyEmojis.FAMILY_MAN_BOY]: { name: "Family of man and boy", unicode: "U+1F468 U+200D U+1F466", emoji: "👨‍👦" },
  [FamilyEmojis.FAMILY_MAN_BOY_BOY]: { name: "Family of man, boy, and boy", unicode: "U+1F468 U+200D U+1F466 U+200D U+1F466", emoji: "👨‍👦‍👦" },
  [FamilyEmojis.FAMILY_MAN_GIRL]: { name: "Family of man and girl", unicode: "U+1F468 U+200D U+1F467", emoji: "👨‍👧" },
  [FamilyEmojis.FAMILY_MAN_GIRL_BOY]: { name: "Family of man, girl, and boy", unicode: "U+1F468 U+200D U+1F467 U+200D U+1F466", emoji: "👨‍👧‍👦" },
  [FamilyEmojis.FAMILY_MAN_GIRL_GIRL]: { name: "Family of man, girl, and girl", unicode: "U+1F468 U+200D U+1F467 U+200D U+1F467", emoji: "👨‍👧‍👧" },
  [FamilyEmojis.FAMILY_WOMAN_BOY]: { name: "Family of woman, and boy", unicode: "U+1F469 U+200D U+1F466", emoji: "👩‍👦" },
  [FamilyEmojis.FAMILY_WOMAN_BOY_BOY]: { name: "Family of woman, boy, and boy", unicode: "", emoji: "" },
  [FamilyEmojis.FAMILY_WOMAN_GIRL]: { name: "Family of woman, and girl", unicode: "U+1F469 U+200D U+1F467", emoji: "👩‍👧" },
  [FamilyEmojis.FAMILY_WOMAN_GIRL_BOY]: { name: "Family of woman, girl, and boy", unicode: "U+1F469 U+200D U+1F467 U+200D U+1F466", emoji: "👩‍👧‍👦" },
  [FamilyEmojis.FAMILY_WOMAN_GIRL_GIRL]: { name: "Family of woman, girl, and girl", unicode: "U+1F469 U+200D U+1F467 U+200D U+1F467", emoji: "👩‍👧‍👧" },
  [FamilyEmojis.PEOPLE_HOLDING_HANDS]: { name: "People holding hands", unicode: "U+1F9D1 U+200D U+1F91D U+200D U+1F9D1", emoji: "🧑‍🤝‍🧑" },
  [FamilyEmojis.WOMEN_HOLDING_HANDS]: { name: "Women holding hands", unicode: "U+1F46D", emoji: "👭" },
  [FamilyEmojis.WOMAN_AND_MAN_HOLDING_HANDS]: { name: "Woman and man holding hands", unicode: "U+1F46B", emoji: "👫" },
  [FamilyEmojis.MEN_HOLDING_HANDS]: { name: "Men holding hands", unicode: "U+1F46C", emoji: "👬" },
  [FamilyEmojis.KISS]: { name: "Kiss", unicode: "U+1F48F", emoji: "💏" },
  [FamilyEmojis.WOMAN_MAN_KISSING]: { name: "Woman and man kissing", unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F48B U+200D U+1F468", emoji: "👩‍❤️‍💋‍👨" },
  [FamilyEmojis.MAN_MAN_KISSING]: { name: "Man and man kissing", unicode: "U+1F468 U+200D U+2764 U+FE0F U+200D U+1F48B U+200D U+1F468", emoji: "👨‍❤️‍💋‍👨" },
  [FamilyEmojis.WOMAN_WOMAN_KISSING]: { name: "Woman and woman kissing", unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F48B U+200D U+1F469", emoji: "👩‍❤️‍💋‍👩" },
  [FamilyEmojis.WOMAN_MAN_COUPLE]: { name: "Woman and man couple", unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F468", emoji: "👩‍❤️‍👨" },
  [FamilyEmojis.MAN_MAN_COUPLE]: { name: "Man and man couple", unicode: "U+1F468 U+200D U+2764 U+FE0F U+200D U+1F468", emoji: "👨‍❤️‍👨" },
  [FamilyEmojis.WOMAN_WOMAN_COUPLE]: { name: "Woman and woman couple", unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F469", emoji: "👩‍❤️‍👩" },
  [FamilyEmojis.COUPLE_WITH_HEART]: { name: "Couple with heart", unicode: "U+1F491", emoji: "💑" },
  [FamilyEmojis.PERSON_SPEAKING]: { name: "Person speaking", unicode: "U+1F5E3", emoji: "🗣" },
  [FamilyEmojis.BUST_IN_SILHOUHETTE]: { name: "Bust in silhouhette", unicode: "U+1F464", emoji: "👤" },
  [FamilyEmojis.BUSTS_IN_SILHOUETTE]: { name: "Busts in silhouette", unicode: "U+1F465", emoji: "👥" },
  [FamilyEmojis.PEOPLE_HUGGING]: { name: "People hugging", unicode: "U+1FAC2", emoji: "🫂" },
}
