import { type EmojiDefinition } from "./types";

export enum FoodAndDrinksEmojis {
  GRAPES = "grapes",
  MELON = "melon",
  WATER_MELON = "water_melon",
  TANGERINE = "tangerine",
  LIME = "lime",
  BANANA = "banana",
  PINEAPPLE = "pineapple",
  MANGO = "mango",
  RED_APPLE = "red_apple",
  GREEN_APPLE = "green_apple",
  PEAR = "pear",
  PEACH = "peach",
  CHERRIES = "cherries",
  STRAWBERRIES = "strawberries",
  BLUEBERRIES = "blueberries",
  KIWI_FRUIT = "kiwi_fruit",
  TOMATO = "tomato",
  OLIVE = "olive",
  COCONUT = "coconut",
  AVOCADO = "avocado",
  EGGPLANT = "eggplant",
  POTATO = "potato",
  CARROT = "carrot",
  CORN = "corn",
  PEPPER = "pepper",
  BELL_PEPPER = "bell_pepper",
  CUCUMBER = "cucumber",
  LEAFY_GREEN = "leafy_green",
  BROCCOLI = "broccoli",
  GARLIC = "garlic",
  ONION = "onion",
  MUSHROOM = "mushroom",
  PEANUTS = "peanuts",
  BEANS = "beans",
  CHESTNUT = "chestnut",
  BREAD = "bread",
  CROISSANT = "croissant",
  BAGUETTE_BREAD = "baguette_bread",
  FLAT_BREAD = "flat_bread",
  PRETZEL = "pretzel",
  BAGEL = "bagel",
  PANCAKE = "pancake",
  WAFFLE = "waffle",
  CHEESE_WEDGE = "cheese_wedge",
  MEAT_WITH_BONE = "meat_with_bone",
  POULTRY_LEG = "poultry_leg",
  CUT_OF_MEAT = "cut_of_meat",
  BACON = "bacon",
  HAMBURGER = "hamburger",
  FRENCH_FRIES = "french_fries",
  PIZZA = "pizza",
  HOT_DOG = "hot_dog",
  SANDWICH = "sandwich",
  TACO = "taco",
  BURRITO = "burrito",
  TAMALE = "tamale",
  STUFFED_FLATBREAD = "stuffed_flatbread",
  FALAFEL = "falafel",
  EGG = "egg",
  COOKING = "cooking",
  SHALLOW_PAN_OF_FOOD = "shallow_pan_of_food",
  POT_OF_FOOD = "pot_of_food",
  FONDUE = "fondue",
  BOWL_WITH_FOOD = "bowl_with_food",
  GREEN_SALAD = "green_salad",
  POPCORN = "popcorn",
  BUTTER = "butter",
  SALT = "salt",
  CANNED_FOOD = "canned_food",
  BENTO_BOX = "bento_box",
  RICE_CRACKER = "rice_cracker",
  RICE_BALL = "rice_ball",
  COOKED_RICE = "cooked_rice",
  CURRY_RICE = "curry_rice",
  STEAMING_BOWL = "steaming_bowl",
  SPAGHETTI = "spaghetti",
  ROASTED_SWEET_POTATO = "roasted_sweet_potato",
  ODEN = "oden",
  SUSHI = "sushi",
  FRIED_SHRIMP = "fried_shrimp",
  FISH_CAKE_WITH_SWIRI = "fish_cake_with_swiri",
  MOON_CAKE = "moon_cake",
  DANGO = "dango",
  DUMPLING = "dumpling",
  FORTUNE_COOKIE = "fortune_cookie",
  TAKE_OUT_BOX = "take_out_box",
  CRAB = "crab",
  LOBSTER = "lobster",
  SHRIMP = "shrimp",
  SQUID = "squid",
  OYSTER = "oyster",
  ICE_CREAM = "ice_cream",
  SHAVED_ICE_CREAM = "shaved_ice_cream",
  SOFT_ICE_CREAM = "soft_ice_cream",
  DOUGHNUT = "doughnut",
  COOKIE = "cookie",
  BIRTHDAY_CAKE = "birthday_cake",
  SHORT_CAKE = "short_cake",
  CUP_CAKE = "cup_cake",
  PIE = "pie",
  CHOCOLATE = "chocolate",
  CANDY = "candy",
  LOLLIPOP = "lollipop",
  CUSTARD = "custard",
  HONEY_POT = "honey_pot",
  BABY_BOTTLE = "baby_bottle",
  GLASS_OF_MILK = "glass_of_milk",
  HOT_BEVERAGE = "hot_beverage",
  TEAPOT = "teapot",
  TEACUP_WITHOUT_HANDLE = "teacup_without_handle",
  SAKE = "sake",
  BOTTLE_WITH_POPPIN_CORK = "bottle_with_poppin_cork",
  WINE_GLASS = "wine_glass",
  COCKTAIL_GLASS = "cocktail_glass",
  TROPICAL_DRINK = "tropical_drink",
  BEER_MUG = "beer_mug",
  CLINKING_BEER_MUG = "clinking_beer_mug",
  CLINKING_GLASSES = "clinking_glasses",
  TUMBLER_GLASS = "tumbler_glass",
  CUP_WITH_STRAWBERRY = "cup_with_strawberry",
  BUBBLE_TEA = "bubble_tea",
  BEVERAGE_BOX = "beverage_box",
  MATE_DRINK = "mate_drink",
  ICE = "ice",
  CHOPSTICKS = "chopsticks",
  FORK_AND_KNIFE_WITH_PLATE = "fork_and_knife_with_plate",
  FORK_AND_KNIFE = "fork_and_knife",
  SPOON = "spoon",
  KITCHEN_KNIFE = "kitchen_knife",
  JAR = "jar",
  AMPHORA = "amphora",
}

export const foodAndDrinksEmojis: Record<FoodAndDrinksEmojis, EmojiDefinition> = {
  [FoodAndDrinksEmojis.GRAPES]: { name: "Grapes", unicode: "U+1F347", emoji: "🍇" },
  [FoodAndDrinksEmojis.MELON]: { name: "Melon", unicode: "U+1F348", emoji: "🍈" },
  [FoodAndDrinksEmojis.WATER_MELON]: { name: "Water melon", unicode: "U+1F349", emoji: "🍉" },
  [FoodAndDrinksEmojis.TANGERINE]: { name: "Tangerine", unicode: "U+1F34A", emoji: "🍊" },
  [FoodAndDrinksEmojis.LIME]: { name: "Lime", unicode: "U+1F34B", emoji: "🍋" },
  [FoodAndDrinksEmojis.BANANA]: { name: "Banana", unicode: "U+1F34C", emoji: "🍌" },
  [FoodAndDrinksEmojis.PINEAPPLE]: { name: "Pineapple", unicode: "U+1F34D", emoji: "🍍" },
  [FoodAndDrinksEmojis.MANGO]: { name: "Mango", unicode: "U+1F96D", emoji: "🥭" },
  [FoodAndDrinksEmojis.RED_APPLE]: { name: "Red apple", unicode: "U+1F34E", emoji: "🍎" },
  [FoodAndDrinksEmojis.GREEN_APPLE]: { name: "Green apple", unicode: "U+1F34F", emoji: "🍏" },
  [FoodAndDrinksEmojis.PEAR]: { name: "Pear", unicode: "U+1F350", emoji: "🍐" },
  [FoodAndDrinksEmojis.PEACH]: { name: "Peach", unicode: "U+1F351", emoji: "🍑" },
  [FoodAndDrinksEmojis.CHERRIES]: { name: "Cherries", unicode: "U+1F352", emoji: "🍒" },
  [FoodAndDrinksEmojis.STRAWBERRIES]: { name: "Strawberries", unicode: "U+1F353", emoji: "🍓" },
  [FoodAndDrinksEmojis.BLUEBERRIES]: { name: "Blueberries", unicode: "U+1FAD0", emoji: "🫐" },
  [FoodAndDrinksEmojis.KIWI_FRUIT]: { name: "Kiwi fruit", unicode: "U+1F95D", emoji: "🥝" },
  [FoodAndDrinksEmojis.TOMATO]: { name: "Tomato", unicode: "U+1F345", emoji: "🍅" },
  [FoodAndDrinksEmojis.OLIVE]: { name: "Olive", unicode: "U+1FAD2", emoji: "🫒" },
  [FoodAndDrinksEmojis.COCONUT]: { name: "Coconut", unicode: "U+1F965", emoji: "🥥" },
  [FoodAndDrinksEmojis.AVOCADO]: { name: "Avocado", unicode: "U+1F951", emoji: "🥑" },
  [FoodAndDrinksEmojis.EGGPLANT]: { name: "Eggplant", unicode: "U+1F346", emoji: "🍆" },
  [FoodAndDrinksEmojis.POTATO]: { name: "Potato", unicode: "U+1F954", emoji: "🥔" },
  [FoodAndDrinksEmojis.CARROT]: { name: "Carrot", unicode: "U+1F955", emoji: "🥕" },
  [FoodAndDrinksEmojis.CORN]: { name: "Corn", unicode: "U+1F33D", emoji: "🌽" },
  [FoodAndDrinksEmojis.PEPPER]: { name: "Pepper", unicode: "U+1F336", emoji: "🌶" },
  [FoodAndDrinksEmojis.BELL_PEPPER]: { name: "Bell pepper", unicode: "U+1FAD1", emoji: "🫑" },
  [FoodAndDrinksEmojis.CUCUMBER]: { name: "Cucumber", unicode: "U+1F952", emoji: "🥒" },
  [FoodAndDrinksEmojis.LEAFY_GREEN]: { name: "Leafy green", unicode: "U+1F96C", emoji: "🥬" },
  [FoodAndDrinksEmojis.BROCCOLI]: { name: "Broccoli", unicode: "U+1F966", emoji: "🥦" },
  [FoodAndDrinksEmojis.GARLIC]: { name: "Garlic", unicode: "U+1F9C4", emoji: "🧄" },
  [FoodAndDrinksEmojis.ONION]: { name: "Onion", unicode: "U+1F9C5", emoji: "🧅" },
  [FoodAndDrinksEmojis.MUSHROOM]: { name: "Mushroom", unicode: "U+1F344", emoji: "🍄" },
  [FoodAndDrinksEmojis.PEANUTS]: { name: "Peanuts", unicode: "U+1F95C", emoji: "🥜" },
  [FoodAndDrinksEmojis.BEANS]: { name: "Beans", unicode: "U+1FAD8", emoji: "🫘" },
  [FoodAndDrinksEmojis.CHESTNUT]: { name: "Chestnut", unicode: "U+1F330", emoji: "🌰" },
  [FoodAndDrinksEmojis.BREAD]: { name: "Bread", unicode: "U+1F35E", emoji: "🍞" },
  [FoodAndDrinksEmojis.CROISSANT]: { name: "Croissant", unicode: "U+1F950", emoji: "🥐" },
  [FoodAndDrinksEmojis.BAGUETTE_BREAD]: { name: "Baguette bread", unicode: "U+1F956", emoji: "🥖" },
  [FoodAndDrinksEmojis.FLAT_BREAD]: { name: "Flat bread", unicode: "U+1FAD3", emoji: "🫓" },
  [FoodAndDrinksEmojis.PRETZEL]: { name: "Pretzel", unicode: "U+1F968", emoji: "🥨" },
  [FoodAndDrinksEmojis.BAGEL]: { name: "Bagel", unicode: "U+1F96F", emoji: "🥯" },
  [FoodAndDrinksEmojis.PANCAKE]: { name: "Pancake", unicode: "U+1F95E", emoji: "🥞" },
  [FoodAndDrinksEmojis.WAFFLE]: { name: "Waffle", unicode: "U+1F9C7", emoji: "🧇" },
  [FoodAndDrinksEmojis.CHEESE_WEDGE]: { name: "Cheese wedge", unicode: "U+1F9C0", emoji: "🧀" },
  [FoodAndDrinksEmojis.MEAT_WITH_BONE]: { name: "Meat with bone", unicode: "U+1F356", emoji: "🍖" },
  [FoodAndDrinksEmojis.POULTRY_LEG]: { name: "Poultry leg", unicode: "U+1F357", emoji: "🍗" },
  [FoodAndDrinksEmojis.CUT_OF_MEAT]: { name: "Cut of meat", unicode: "U+1F969", emoji: "🥩" },
  [FoodAndDrinksEmojis.BACON]: { name: "Bacon", unicode: "U+1F953", emoji: "🥓" },
  [FoodAndDrinksEmojis.HAMBURGER]: { name: "Hamburger", unicode: "U+1F354", emoji: "🍔" },
  [FoodAndDrinksEmojis.FRENCH_FRIES]: { name: "French fries", unicode: "U+1F35F", emoji: "🍟" },
  [FoodAndDrinksEmojis.PIZZA]: { name: "Pizza", unicode: "U+1F355", emoji: "🍕" },
  [FoodAndDrinksEmojis.HOT_DOG]: { name: "Hot dog", unicode: "U+1F32D", emoji: "🌭" },
  [FoodAndDrinksEmojis.SANDWICH]: { name: "Sandwich", unicode: "U+1F96A", emoji: "🥪" },
  [FoodAndDrinksEmojis.TACO]: { name: "Taco", unicode: "U+1F32E", emoji: "🌮" },
  [FoodAndDrinksEmojis.BURRITO]: { name: "Burrito", unicode: "U+1F32F", emoji: "🌯" },
  [FoodAndDrinksEmojis.TAMALE]: { name: "Tamale", unicode: "U+1FAD4", emoji: "🫔" },
  [FoodAndDrinksEmojis.STUFFED_FLATBREAD]: { name: "Stuffed flatbread", unicode: "U+1F959", emoji: "🥙" },
  [FoodAndDrinksEmojis.FALAFEL]: { name: "Falafel", unicode: "U+1F9C6", emoji: "🧆" },
  [FoodAndDrinksEmojis.EGG]: { name: "Egg", unicode: "U+1F95A", emoji: "🥚" },
  [FoodAndDrinksEmojis.COOKING]: { name: "Cooking", unicode: "U+1F373", emoji: "🍳" },
  [FoodAndDrinksEmojis.SHALLOW_PAN_OF_FOOD]: { name: "Shallow pan of food", unicode: "U+1F958", emoji: "🥘" },
  [FoodAndDrinksEmojis.POT_OF_FOOD]: { name: "Pot of food", unicode: "U+1F372", emoji: "🍲" },
  [FoodAndDrinksEmojis.FONDUE]: { name: "Fondue", unicode: "U+1FAD5", emoji: "🫕" },
  [FoodAndDrinksEmojis.BOWL_WITH_FOOD]: { name: "Bowl with food", unicode: "U+1F963", emoji: "🥣" },
  [FoodAndDrinksEmojis.GREEN_SALAD]: { name: "Green salad", unicode: "U+1F957", emoji: "🥗" },
  [FoodAndDrinksEmojis.POPCORN]: { name: "Popcorn", unicode: "U+1F37F", emoji: "🍿" },
  [FoodAndDrinksEmojis.BUTTER]: { name: "Butter", unicode: "U+1F9C8", emoji: "🧈" },
  [FoodAndDrinksEmojis.SALT]: { name: "Salt", unicode: "U+1F9C2", emoji: "🧂" },
  [FoodAndDrinksEmojis.CANNED_FOOD]: { name: "Canned food", unicode: "U+1F96B", emoji: "🥫" },
  [FoodAndDrinksEmojis.BENTO_BOX]: { name: "Bento box", unicode: "U+1F371", emoji: "🍱" },
  [FoodAndDrinksEmojis.RICE_CRACKER]: { name: "RIce cracker", unicode: "U+1F358", emoji: "🍘" },
  [FoodAndDrinksEmojis.RICE_BALL]: { name: "Rice ball", unicode: "U+1F359", emoji: "🍙" },
  [FoodAndDrinksEmojis.COOKED_RICE]: { name: "Cooked rice", unicode: "U+1F35A", emoji: "🍚" },
  [FoodAndDrinksEmojis.CURRY_RICE]: { name: "Curry rice", unicode: "U+1F35B", emoji: "🍛" },
  [FoodAndDrinksEmojis.STEAMING_BOWL]: { name: "Steaming bowl", unicode: "U+1F35C", emoji: "🍜" },
  [FoodAndDrinksEmojis.SPAGHETTI]: { name: "Spaghetti", unicode: "U+1F35D", emoji: "🍝" },
  [FoodAndDrinksEmojis.ROASTED_SWEET_POTATO]: { name: "Roasted sweet potato", unicode: "U+1F360", emoji: "🍠" },
  [FoodAndDrinksEmojis.ODEN]: { name: "Oden", unicode: "U+1F362", emoji: "🍢" },
  [FoodAndDrinksEmojis.SUSHI]: { name: "Sushi", unicode: "U+1F363", emoji: "🍣" },
  [FoodAndDrinksEmojis.FRIED_SHRIMP]: { name: "Fried shrimp", unicode: "U+1F364", emoji: "🍤" },
  [FoodAndDrinksEmojis.FISH_CAKE_WITH_SWIRI]: { name: "Fish cake with swiri", unicode: "U+1F365", emoji: "🍥" },
  [FoodAndDrinksEmojis.MOON_CAKE]: { name: "Moon cake", unicode: "U+1F96E", emoji: "🥮" },
  [FoodAndDrinksEmojis.DANGO]: { name: "Dango", unicode: "U+1F361", emoji: "🍡" },
  [FoodAndDrinksEmojis.DUMPLING]: { name: "Dumpling", unicode: "U+1F95F", emoji: "🥟" },
  [FoodAndDrinksEmojis.FORTUNE_COOKIE]: { name: "Fortune cookie", unicode: "U+1F960", emoji: "🥠" },
  [FoodAndDrinksEmojis.TAKE_OUT_BOX]: { name: "Take out box", unicode: "U+1F961", emoji: "🥡" },
  [FoodAndDrinksEmojis.CRAB]: { name: "Crab", unicode: "U+1F980", emoji: "🦀" },
  [FoodAndDrinksEmojis.LOBSTER]: { name: "Lobster", unicode: "U+1F99E", emoji: "🦞" },
  [FoodAndDrinksEmojis.SHRIMP]: { name: "Shrimp", unicode: "U+1F990", emoji: "🦐" },
  [FoodAndDrinksEmojis.SQUID]: { name: "Squid", unicode: "U+1F991", emoji: "🦑" },
  [FoodAndDrinksEmojis.OYSTER]: { name: "Oyster", unicode: "U+1F9AA", emoji: "🦪" },
  [FoodAndDrinksEmojis.ICE_CREAM]: { name: "Ice cream", unicode: "U+1F368", emoji: "🍨" },
  [FoodAndDrinksEmojis.SHAVED_ICE_CREAM]: { name: "Shaved ice cream", unicode: "U+1F367", emoji: "🍧" },
  [FoodAndDrinksEmojis.SOFT_ICE_CREAM]: { name: "Soft ice cream", unicode: "U+1F366", emoji: "🍦" },
  [FoodAndDrinksEmojis.DOUGHNUT]: { name: "Doughnut", unicode: "U+1F369", emoji: "🍩" },
  [FoodAndDrinksEmojis.COOKIE]: { name: "Cookie", unicode: "U+1F36A", emoji: "🍪" },
  [FoodAndDrinksEmojis.BIRTHDAY_CAKE]: { name: "Birthday cake", unicode: "U+1F382", emoji: "🎂" },
  [FoodAndDrinksEmojis.SHORT_CAKE]: { name: "Short cake", unicode: "U+1F370", emoji: "🍰" },
  [FoodAndDrinksEmojis.CUP_CAKE]: { name: "Cup cake", unicode: "U+1F9C1", emoji: "🧁" },
  [FoodAndDrinksEmojis.PIE]: { name: "Pie", unicode: "U+1F967", emoji: "🥧" },
  [FoodAndDrinksEmojis.CHOCOLATE]: { name: "Chocolate", unicode: "U+1F36B", emoji: "🍫" },
  [FoodAndDrinksEmojis.CANDY]: { name: "Candy", unicode: "U+1F36C", emoji: "🍬" },
  [FoodAndDrinksEmojis.LOLLIPOP]: { name: "Lollipop", unicode: "U+1F36D", emoji: "🍭" },
  [FoodAndDrinksEmojis.CUSTARD]: { name: "Custard", unicode: "U+1F36E", emoji: "🍮" },
  [FoodAndDrinksEmojis.HONEY_POT]: { name: "Honey pot", unicode: "U+1F36F", emoji: "🍯" },
  [FoodAndDrinksEmojis.BABY_BOTTLE]: { name: "Baby bottle", unicode: "U+1F37C", emoji: "🍼" },
  [FoodAndDrinksEmojis.GLASS_OF_MILK]: { name: "Glass of milk", unicode: "U+1F95B", emoji: "🥛" },
  [FoodAndDrinksEmojis.HOT_BEVERAGE]: { name: "Hot beverage", unicode: "U+2615", emoji: "☕" },
  [FoodAndDrinksEmojis.TEAPOT]: { name: "Teapot", unicode: "U+1FAD6", emoji: "🫖" },
  [FoodAndDrinksEmojis.TEACUP_WITHOUT_HANDLE]: { name: "Teacup without handle", unicode: "U+1F375", emoji: "🍵" },
  [FoodAndDrinksEmojis.SAKE]: { name: "Sake", unicode: "U+1F376", emoji: "🍶" },
  [FoodAndDrinksEmojis.BOTTLE_WITH_POPPIN_CORK]: { name: "Bottle with poppin cork", unicode: "U+1F37E", emoji: "🍾" },
  [FoodAndDrinksEmojis.WINE_GLASS]: { name: "Wine glass", unicode: "U+1F377", emoji: "🍷" },
  [FoodAndDrinksEmojis.COCKTAIL_GLASS]: { name: "Cocktail glass", unicode: "U+1F378", emoji: "🍸" },
  [FoodAndDrinksEmojis.TROPICAL_DRINK]: { name: "Tropical drink", unicode: "U+1F379", emoji: "🍹" },
  [FoodAndDrinksEmojis.BEER_MUG]: { name: "Beer mug", unicode: "U+1F37A", emoji: "🍺" },
  [FoodAndDrinksEmojis.CLINKING_BEER_MUG]: { name: "Clinking beer mug", unicode: "U+1F37B", emoji: "🍻" },
  [FoodAndDrinksEmojis.CLINKING_GLASSES]: { name: "Clinking glasses", unicode: "U+1F942", emoji: "🥂" },
  [FoodAndDrinksEmojis.TUMBLER_GLASS]: { name: "Tumbler glass", unicode: "U+1F943", emoji: "🥃" },
  [FoodAndDrinksEmojis.CUP_WITH_STRAWBERRY]: { name: "Cup with strawberry", unicode: "U+1F964", emoji: "🥤" },
  [FoodAndDrinksEmojis.BUBBLE_TEA]: { name: "Bubble tea", unicode: "U+1F9CB", emoji: "🧋" },
  [FoodAndDrinksEmojis.BEVERAGE_BOX]: { name: "Beverage box", unicode: "U+1F9C3", emoji: "🧃" },
  [FoodAndDrinksEmojis.MATE_DRINK]: { name: "Mate drink", unicode: "U+1F9C9", emoji: "🧉" },
  [FoodAndDrinksEmojis.ICE]: { name: "Ice", unicode: "U+1F9CA", emoji: "🧊" },
  [FoodAndDrinksEmojis.CHOPSTICKS]: { name: "Chopsticks", unicode: "U+1F962", emoji: "🥢" },
  [FoodAndDrinksEmojis.FORK_AND_KNIFE_WITH_PLATE]: { name: "Fork and knife with plate", unicode: "U+1F37D", emoji: "🍽" },
  [FoodAndDrinksEmojis.FORK_AND_KNIFE]: { name: "Fork and knife", unicode: "U+1F374", emoji: "🍴" },
  [FoodAndDrinksEmojis.SPOON]: { name: "Spoon", unicode: "U+1F944", emoji: "🥄" },
  [FoodAndDrinksEmojis.KITCHEN_KNIFE]: { name: "Kitchen knife", unicode: "U+1F52A", emoji: "🔪" },
  [FoodAndDrinksEmojis.JAR]: { name: "Jar", unicode: "U+1FAD9", emoji: "🫙" },
  [FoodAndDrinksEmojis.AMPHORA]: { name: "Amphora", unicode: "U+1F3FA", emoji: "🏺" },
}
