import { type EmojiDefinition } from "./types";

export enum GamesEmojis {
  BULLSEYE = "bullseye",
  YOYO = "yoyo",
  KITE = "kite",
  EIGHT_BALL = "eight_ball",
  CRYSTAL_BALL = "crystal_ball",
  MAGIC_WAND = "magic_wand",
  NAZAR_AMULET = "nazar_amulet",
  HAMSA = "hamsa",
  VIDEO_GAME_PAD = "video_game_pad",
  JOYSTICK = "joystick",
  SLOT_MACHINE = "slot_machine",
  GAME_DIE = "game_die",
  PUZZLE_PIECE = "puzzle_piece",
  TEDDY_BEAR = "teddy_bear",
  PINATA = "pinata",
  NESTING_DOLL = "nesting_doll",
  SPADE_SUIT = "spade_suit",
  HEART_SUIT = "heart_suit",
  CLUB_SUIT = "club_suit",
  CHESS_PAWN = "chess_pawn",
  JOKER = "joker",
  MAHJONG_RED_DRAGON = "mahjong_red_dragon",
  FLOWER_PLAYING_CARDS = "flower_playing_cards",
}

export const gamesEmojis: Record<GamesEmojis, EmojiDefinition> = {
  [GamesEmojis.BULLSEYE]: { name: "Bullseye", unicode: "U+1F3AF", emoji: "🎯" },
  [GamesEmojis.YOYO]: { name: "Yo-yo", unicode: "U+1FA80", emoji: "🪀" },
  [GamesEmojis.KITE]: { name: "Kite", unicode: "U+1FA81", emoji: "🪁" },
  [GamesEmojis.EIGHT_BALL]: { name: "8 ball", unicode: "U+1F3B1", emoji: "🎱" },
  [GamesEmojis.CRYSTAL_BALL]: { name: "Crystal ball", unicode: "U+1F52E", emoji: "🔮" },
  [GamesEmojis.MAGIC_WAND]: { name: "Magic wand", unicode: "U+1FA84", emoji: "🪄" },
  [GamesEmojis.NAZAR_AMULET]: { name: "Nazar amulet", unicode: "U+1F9FF", emoji: "🧿" },
  [GamesEmojis.HAMSA]: { name: "Hamsa", unicode: "U+1FAAC", emoji: "🪬" },
  [GamesEmojis.VIDEO_GAME_PAD]: { name: "Video game pad", unicode: "U+1F3AE", emoji: "🎮" },
  [GamesEmojis.JOYSTICK]: { name: "Joystick", unicode: "U+1F579", emoji: "🕹" },
  [GamesEmojis.SLOT_MACHINE]: { name: "Slot machine", unicode: "U+1F3B0", emoji: "🎰" },
  [GamesEmojis.GAME_DIE]: { name: "Game die", unicode: "U+1F3B2", emoji: "🎲" },
  [GamesEmojis.PUZZLE_PIECE]: { name: "Puzzle piece", unicode: "U+1F9E9", emoji: "🧩" },
  [GamesEmojis.TEDDY_BEAR]: { name: "Teddy bear", unicode: "U+1F9F8", emoji: "🧸" },
  [GamesEmojis.PINATA]: { name: "Piñata", unicode: "U+1FA85", emoji: "🪅" },
  [GamesEmojis.NESTING_DOLL]: { name: "Nesting doll", unicode: "U+1FA86", emoji: "🪆" },
  [GamesEmojis.SPADE_SUIT]: { name: "Spade suit", unicode: "U+2660", emoji: "♠" },
  [GamesEmojis.HEART_SUIT]: { name: "Heart suit", unicode: "U+2665", emoji: "♥" },
  [GamesEmojis.CLUB_SUIT]: { name: "Club suit", unicode: "U+2663", emoji: "♣" },
  [GamesEmojis.CHESS_PAWN]: { name: "Chess pawn", unicode: "U+265F", emoji: "♟" },
  [GamesEmojis.JOKER]: { name: "Joker", unicode: "U+1F0CF", emoji: "🃏" },
  [GamesEmojis.MAHJONG_RED_DRAGON]: { name: "Mahjong red dragon", unicode: "U+1F004", emoji: "🀄" },
  [GamesEmojis.FLOWER_PLAYING_CARDS]: { name: "Flower playing cards", unicode: "U+1F3B4", emoji: "🎴" },
}
