import { type EmojiDefinition } from "./types";

export enum GeometricEmojis {
  RED_CIRCLE = "red_circle",
  ORANGE_CIRCLE = "orange_circle",
  YELLOW_CIRCLE = "yellow_circle",
  GREEN_CIRCLE = "green_circle",
  BLUE_CIRCLE = "blue_circle",
  PURPLE_CIRCLE = "purple_circle",
  BROWN_CIRCLE = "brown_circle",
  BLACK_CIRCLE = "black_circle",
  WHITE_CIRCLE = "white_circle",
  RED_SQUARE = "red_square",
  ORANGE_SQUARE = "orange_square",
  YELLOW_SQUARE = "yellow_square",
  GREEN_SQUARE = "green_square",
  BLUE_SQUARE = "blue_square",
  PURPLE_SQUARE = "purple_square",
  BROWN_SQUARE = "brown_square",
  BLACK_SQUARE = "black_square",
  WHITE_SQUARE = "white_square",
  LARGE_ORANGE_DIAMOND = "large_orange_diamond",
  LARGE_BLUE_DIAMOND = "large_blue_diamond",
  SMALL_ORANGE_DIAMOND = "small_orange_diamond",
  SMALL_BLUE_DIAMOND = "small_blue_diamond",
  RED_TRIANGLE_POINTED_UP = "red_triangle_pointed_up",
  RED_TRIANGLE_POINTED_DOWN = "red_triangle_pointed_down",
  DIAMOND_WITH_A_DOT = "diamond_with_a_dot",
  RADIO_BUTTON = "radio_button",
  WHITE_SQUARE_BUTTON = "white_square_button",
  BLACK_SQUARE_BUTTON = "black_square_button",
}

export const geometricEmojis: Record<GeometricEmojis, EmojiDefinition> = {
  [GeometricEmojis.RED_CIRCLE]: { name: "Red circle", unicode: "U+1F534", emoji: "🔴" },
  [GeometricEmojis.ORANGE_CIRCLE]: { name: "Orange circle", unicode: "U+1F7E0", emoji: "🟠" },
  [GeometricEmojis.YELLOW_CIRCLE]: { name: "Yellow circle", unicode: "U+1F7E1", emoji: "🟡" },
  [GeometricEmojis.GREEN_CIRCLE]: { name: "Green circle", unicode: "U+1F7E2", emoji: "🟢" },
  [GeometricEmojis.BLUE_CIRCLE]: { name: "Blue circle", unicode: "U+1F535", emoji: "🔵" },
  [GeometricEmojis.PURPLE_CIRCLE]: { name: "Purple circle", unicode: "U+1F7E3", emoji: "🟣" },
  [GeometricEmojis.BROWN_CIRCLE]: { name: "Brown circle", unicode: "U+1F7E4", emoji: "🟤" },
  [GeometricEmojis.BLACK_CIRCLE]: { name: "Black circle", unicode: "U+26AB", emoji: "⚫" },
  [GeometricEmojis.WHITE_CIRCLE]: { name: "White circle", unicode: "U+26AA", emoji: "⚪" },
  [GeometricEmojis.RED_SQUARE]: { name: "Red square", unicode: "U+1F7E5", emoji: "🟥" },
  [GeometricEmojis.ORANGE_SQUARE]: { name: "Orange square", unicode: "U+1F7E5", emoji: "🟧" },
  [GeometricEmojis.YELLOW_SQUARE]: { name: "Yellow square", unicode: "U+1F7E8", emoji: "🟨" },
  [GeometricEmojis.GREEN_SQUARE]: { name: "Green square", unicode: "U+1F7E9", emoji: "🟩" },
  [GeometricEmojis.BLUE_SQUARE]: { name: "Blue square", unicode: "U+1F7E6", emoji: "🟦" },
  [GeometricEmojis.PURPLE_SQUARE]: { name: "Purple square", unicode: "U+1F7EA", emoji: "🟪" },
  [GeometricEmojis.BROWN_SQUARE]: { name: "Brown square", unicode: "U+1F7EB", emoji: "🟫" },
  [GeometricEmojis.BLACK_SQUARE]: { name: "Black square", unicode: "U+2B1B", emoji: "⬛" },
  [GeometricEmojis.WHITE_SQUARE]: { name: "White square", unicode: "U+2B1C", emoji: "⬜" },
  [GeometricEmojis.LARGE_ORANGE_DIAMOND]: { name: "Large orange diamond", unicode: "U+1F536", emoji: "🔶" },
  [GeometricEmojis.LARGE_BLUE_DIAMOND]: { name: "Large blue diamond", unicode: "U+1F537", emoji: "🔷" },
  [GeometricEmojis.SMALL_ORANGE_DIAMOND]: { name: "Small orange diamond", unicode: "U+1F538", emoji: "🔸" },
  [GeometricEmojis.SMALL_BLUE_DIAMOND]: { name: "Small blue diamond", unicode: "U+1F539", emoji: "🔹" },
  [GeometricEmojis.RED_TRIANGLE_POINTED_UP]: { name: "Red triangle pointed up", unicode: "U+1F53A", emoji: "🔺" },
  [GeometricEmojis.RED_TRIANGLE_POINTED_DOWN]: { name: "Red triangle pointed down", unicode: "U+1F53B", emoji: "🔻" },
  [GeometricEmojis.DIAMOND_WITH_A_DOT]: { name: "Diamond with a dot", unicode: "U+1F4A0", emoji: "💠" },
  [GeometricEmojis.RADIO_BUTTON]: { name: "Radio button", unicode: "U+1F518", emoji: "🔘" },
  [GeometricEmojis.WHITE_SQUARE_BUTTON]: { name: "White square button", unicode: "U+1F533", emoji: "🔳" },
  [GeometricEmojis.BLACK_SQUARE_BUTTON]: { name: "Black square button", unicode: "U+1F532", emoji: "🔲" },
}
