import { type EmojiDefinition } from "./types";

export enum HandsAndOtherBodyPartsEmojis {
  WAVING_HAND = "waving_hand",
  RAISED_BACK_OF_HAND = "raised_back_of_hand",
  HANDS_WITH_SPLAYED_FINGER = "hands_with_splayed_finger",
  RAISED_HAND = "raised_hand",
  VULCAN_SALUTE = "vulcan_salute",
  OK = "ok",
  PINCHED_FINGERS = "pinched_fingers",
  PINCHED_HAND = "pinched_hand",
  VICTORY_HAND = "victory_hand",
  CROSSED_FINGERS = "crossed_fingers",
  LOVE_YOU = "love_you",
  HORN_SIGN = "horn_sign",
  CALL_ME_HAND = "call_me_hand",
  INDEX_FINGER_POINTING_LEFT = "index_finger_pointing_left",
  INDEX_FINGER_POINTING_RIGHT = "index_finger_pointing_right",
  INDEX_FINGER_POINTING_UP = "index_finger_pointing_up",
  INDEX_FINGER_POINTING_DOWN = "index_finger_pointing_down",
  MIDDLE_FINGER = "middle_finger",
  FOREHAND_INDEX_FINGER_POINTING_UP = "forehand_index_finger_pointing_up",
  INDEX_FINGER_POINTING_AT_VIEWER = "index_finger_pointing_at_viewer",
  THUMBS_UP = "thumbs_up",
  THUMBS_DOWN = "thumbs_down",
  RAISED_FIST = "raised_fist",
  FIST = "fist",
  LEFT_FACING_FIST = "left_facing_fist",
  RIGHT_FACING_FIST = "right_facing_fist",
  CLAPPING_HANDS = "clapping_hands",
  RAISED_HANDS = "raised_hands",
  OPEN_HANDS = "open_hands",
  PALMS_TOGETHER_HANDS = "palms_together_hands",
  HANDSHAKE = "handshake",
  PRAYING_HANDS = "praying_hands",
  WRITING_HANDS = "writing_hands",
  NAIL_POLISH = "nail_polish",
  SELFIE_HAND = "selfie_hand",
  FLEXED_BICEPS = "flexed_biceps",
  MECHANICAL_ARM = "mechanical_arm",
  LEG = "leg",
  MECHANICAL_LEG = "mechanical_leg",
  FOOT = "foot",
  EAR = "ear",
  EAR_WITH_EARING_AID = "ear_with_earing_aid",
  NOSE = "nose",
  BRAIN = "brain",
  FOOTPRINT = "footprint",
  MECHANICAL_HEART = "mechanical_heart",
  LUNGS = "lungs",
  TOOTH = "tooth",
  BONE = "bone",
  EYES = "eyes",
  EYE = "eye",
  NOSE_2 = "nose_2",
  MOUTH = "mouth",
}

export const handsAndOtherBodyPartsEmojis: Record<HandsAndOtherBodyPartsEmojis, EmojiDefinition> =
{
  [HandsAndOtherBodyPartsEmojis.WAVING_HAND]: {
    name: "Waving hand",
    unicode: "U+1F44B",
    emoji: "👋",
  },
  [HandsAndOtherBodyPartsEmojis.RAISED_BACK_OF_HAND]: {
    name: "Raised back of hand",
    unicode: "U+1F91A",
    emoji: "🤚",
  },
  [HandsAndOtherBodyPartsEmojis.HANDS_WITH_SPLAYED_FINGER]: {
    name: "Hands with splayed finger",
    unicode: "U+1F590",
    emoji: "🖐",
  },
  [HandsAndOtherBodyPartsEmojis.RAISED_HAND]: {
    name: "Raised hand",
    unicode: "U+270B",
    emoji: "✋",
  },
  [HandsAndOtherBodyPartsEmojis.VULCAN_SALUTE]: {
    name: "Vulcan salute",
    unicode: "U+1F596",
    emoji: "🖖",
  },
  [HandsAndOtherBodyPartsEmojis.OK]: {
    name: "Ok",
    unicode: "U+1F44C",
    emoji: "👌",
  },
  [HandsAndOtherBodyPartsEmojis.PINCHED_FINGERS]: {
    name: "Pinched fingers",
    unicode: "U+1F90C",
    emoji: "🤌",
  },
  [HandsAndOtherBodyPartsEmojis.PINCHED_HAND]: {
    name: "Pinched hand",
    unicode: "U+1F90F",
    emoji: "🤏",
  },
  [HandsAndOtherBodyPartsEmojis.VICTORY_HAND]: {
    name: "Victory hand",
    unicode: "U+270C",
    emoji: "✌",
  },
  [HandsAndOtherBodyPartsEmojis.CROSSED_FINGERS]: {
    name: "Crossed fingers",
    unicode: "U+1F91E",
    emoji: "🤞",
  },
  [HandsAndOtherBodyPartsEmojis.LOVE_YOU]: {
    name: "Love you",
    unicode: "U+1F91F",
    emoji: "🤟",
  },
  [HandsAndOtherBodyPartsEmojis.HORN_SIGN]: {
    name: "Horn sign",
    unicode: "U+1F918",
    emoji: "🤘",
  },
  [HandsAndOtherBodyPartsEmojis.CALL_ME_HAND]: {
    name: "Call me hand",
    unicode: "U+1F919",
    emoji: "🤙",
  },
  [HandsAndOtherBodyPartsEmojis.INDEX_FINGER_POINTING_LEFT]: {
    name: "Index finger pointing left",
    unicode: "U+1F448",
    emoji: "👈",
  },
  [HandsAndOtherBodyPartsEmojis.INDEX_FINGER_POINTING_RIGHT]: {
    name: "Index finger pointing right",
    unicode: "U+1F449",
    emoji: "👉",
  },
  [HandsAndOtherBodyPartsEmojis.INDEX_FINGER_POINTING_UP]: {
    name: "Index finger pointing up",
    unicode: "U+1F446",
    emoji: "👆",
  },
  [HandsAndOtherBodyPartsEmojis.INDEX_FINGER_POINTING_DOWN]: {
    name: "Index finger pointing down",
    unicode: "U+1F447",
    emoji: "👇",
  },
  [HandsAndOtherBodyPartsEmojis.MIDDLE_FINGER]: {
    name: "Middle finger",
    unicode: "U+1F595",
    emoji: "🖕",
  },
  [HandsAndOtherBodyPartsEmojis.FOREHAND_INDEX_FINGER_POINTING_UP]: {
    name: "Forehand Index finger pointing up",
    unicode: "U+261D",
    emoji: "☝",
  },
  [HandsAndOtherBodyPartsEmojis.INDEX_FINGER_POINTING_AT_VIEWER]: {
    name: "Index finger pointing at viewer",
    unicode: "U+1FAF5",
    emoji: "🫵",
  },
  [HandsAndOtherBodyPartsEmojis.THUMBS_UP]: {
    name: "Thumbs up",
    unicode: "U+1F44D",
    emoji: "👍",
  },
  [HandsAndOtherBodyPartsEmojis.THUMBS_DOWN]: {
    name: "Thumbs down",
    unicode: "U+1F44E",
    emoji: "👎",
  },
  [HandsAndOtherBodyPartsEmojis.RAISED_FIST]: {
    name: "Raised fist",
    unicode: "U+270A",
    emoji: "✊",
  },
  [HandsAndOtherBodyPartsEmojis.FIST]: {
    name: "Fist",
    unicode: "U+1F44A",
    emoji: "👊",
  },
  [HandsAndOtherBodyPartsEmojis.LEFT_FACING_FIST]: {
    name: "Left facing fist",
    unicode: "U+1F91B",
    emoji: "🤛",
  },
  [HandsAndOtherBodyPartsEmojis.RIGHT_FACING_FIST]: {
    name: "Right facing fist",
    unicode: "U+1F91C",
    emoji: "🤜",
  },
  [HandsAndOtherBodyPartsEmojis.CLAPPING_HANDS]: {
    name: "Clapping hands",
    unicode: "U+1F44F",
    emoji: "👏",
  },
  [HandsAndOtherBodyPartsEmojis.RAISED_HANDS]: {
    name: "Raised hands",
    unicode: "U+1F64C",
    emoji: "🙌",
  },
  [HandsAndOtherBodyPartsEmojis.OPEN_HANDS]: {
    name: "Open hands",
    unicode: "U+1F450",
    emoji: "👐",
  },
  [HandsAndOtherBodyPartsEmojis.PALMS_TOGETHER_HANDS]: {
    name: "Palms together hands",
    unicode: "U+1F932",
    emoji: "🤲",
  },
  [HandsAndOtherBodyPartsEmojis.HANDSHAKE]: {
    name: "Handshake",
    unicode: "U+1F91D",
    emoji: "🤝",
  },
  [HandsAndOtherBodyPartsEmojis.PRAYING_HANDS]: {
    name: "Praying hands",
    unicode: "U+1F64F",
    emoji: "🙏",
  },
  [HandsAndOtherBodyPartsEmojis.WRITING_HANDS]: {
    name: "Writing hands",
    unicode: "U+270D",
    emoji: "✍",
  },
  [HandsAndOtherBodyPartsEmojis.NAIL_POLISH]: {
    name: "Nail polish",
    unicode: "U+1F485",
    emoji: "💅",
  },
  [HandsAndOtherBodyPartsEmojis.SELFIE_HAND]: {
    name: "Selfie hand",
    unicode: "U+1F933",
    emoji: "🤳",
  },
  [HandsAndOtherBodyPartsEmojis.FLEXED_BICEPS]: {
    name: "Flexed biceps",
    unicode: "U+1F4AA",
    emoji: "💪",
  },
  [HandsAndOtherBodyPartsEmojis.MECHANICAL_ARM]: {
    name: "Mechanical arm",
    unicode: "U+1F9BE",
    emoji: "🦾",
  },
  [HandsAndOtherBodyPartsEmojis.LEG]: {
    name: "Leg",
    unicode: "U+1F9B5",
    emoji: "🦵",
  },
  [HandsAndOtherBodyPartsEmojis.MECHANICAL_LEG]: {
    name: "Mechanical leg",
    unicode: "U+1F9BF",
    emoji: "🦿",
  },
  [HandsAndOtherBodyPartsEmojis.FOOT]: {
    name: "Foot",
    unicode: "U+1F9B6",
    emoji: "🦶",
  },
  [HandsAndOtherBodyPartsEmojis.EAR]: {
    name: "Ear",
    unicode: "U+1F442",
    emoji: "👂",
  },
  [HandsAndOtherBodyPartsEmojis.EAR_WITH_EARING_AID]: {
    name: "Ear with earing aid",
    unicode: "U+1F9BB",
    emoji: "🦻",
  },
  [HandsAndOtherBodyPartsEmojis.NOSE]: {
    name: "Nose",
    unicode: "U+1F443",
    emoji: "👃",
  },
  [HandsAndOtherBodyPartsEmojis.BRAIN]: {
    name: "Brain",
    unicode: "U+1F9E0",
    emoji: "🧠",
  },
  [HandsAndOtherBodyPartsEmojis.FOOTPRINT]: {
    name: "Footprint",
    unicode: "U+1F463",
    emoji: "👣",
  },
  [HandsAndOtherBodyPartsEmojis.MECHANICAL_HEART]: {
    name: "Mechanical heart",
    unicode: "U+1FAC0",
    emoji: "🫀",
  },
  [HandsAndOtherBodyPartsEmojis.LUNGS]: {
    name: "Lungs",
    unicode: "U+1FAC1",
    emoji: "🫁",
  },
  [HandsAndOtherBodyPartsEmojis.TOOTH]: {
    name: "Tooth",
    unicode: "U+1F9B7",
    emoji: "🦷",
  },
  [HandsAndOtherBodyPartsEmojis.BONE]: {
    name: "Bone",
    unicode: "U+1F9B7",
    emoji: "🦴",
  },
  [HandsAndOtherBodyPartsEmojis.EYES]: {
    name: "Eyes",
    unicode: "U+1F440",
    emoji: "👀",
  },
  [HandsAndOtherBodyPartsEmojis.EYE]: {
    name: "Eye",
    unicode: "U+1F441",
    emoji: "👁",
  },
  [HandsAndOtherBodyPartsEmojis.NOSE_2]: {
    name: "Nose",
    unicode: "U+1F445",
    emoji: "👅",
  },
  [HandsAndOtherBodyPartsEmojis.MOUTH]: {
    name: "Mouth",
    unicode: "U+1F444",
    emoji: "👄",
  },
}
