import { type EmojiDefinition } from "./types";

export enum HouseholdEmojis {
  DOOR = "door",
  ELEVATOR = "elevator",
  MIRROR = "mirror",
  WINDOW = "window",
  BED = "bed",
  COUCH_AND_LAMP = "couch_and_lamp",
  CHAIR = "chair",
  TOILET = "toilet",
  PLUNGER = "plunger",
  SHOWER = "shower",
  BATHTUB = "bathtub",
  MOUSE_TRAP = "mouse_trap",
  RAZOR = "razor",
  LOTION_BOTTLE = "lotion_bottle",
  SAFETY_PIN = "safety_pin",
  BROOM = "broom",
  BASKET = "basket",
  ROLL_OF_PAPER = "roll_of_paper",
  BUCKET = "bucket",
  SOAP = "soap",
  BUBBLES = "bubbles",
  TOOTHBRUSH = "toothbrush",
  SPONGE = "sponge",
  FIRE_EXTINGUISHER = "fire_extinguisher",
  SHOPPING_CART = "shopping_cart",
}

export const householdEmojis: Record<HouseholdEmojis, EmojiDefinition> = {
  [HouseholdEmojis.DOOR]: { name: "Door", unicode: "U+1F6AA", emoji: "🚪" },
  [HouseholdEmojis.ELEVATOR]: { name: "Elevator", unicode: "U+1F6D7", emoji: "🛗" },
  [HouseholdEmojis.MIRROR]: { name: "Mirror", unicode: "U+1FA9E", emoji: "🪞" },
  [HouseholdEmojis.WINDOW]: { name: "Window", unicode: "U+1FA9F", emoji: "🪟" },
  [HouseholdEmojis.BED]: { name: "Bed", unicode: "U+1F6CF", emoji: "🛏" },
  [HouseholdEmojis.COUCH_AND_LAMP]: { name: "Couch and lamp", unicode: "U+1F6CB", emoji: "🛋" },
  [HouseholdEmojis.CHAIR]: { name: "Chair", unicode: "U+1FA91", emoji: "🪑" },
  [HouseholdEmojis.TOILET]: { name: "Toilet", unicode: "U+1F6BD", emoji: "🚽" },
  [HouseholdEmojis.PLUNGER]: { name: "Plunger", unicode: "U+1FAA0", emoji: "🪠" },
  [HouseholdEmojis.SHOWER]: { name: "Shower", unicode: "U+1F6BF", emoji: "🚿" },
  [HouseholdEmojis.BATHTUB]: { name: "Bathtub", unicode: "U+1F6C1", emoji: "🛁" },
  [HouseholdEmojis.MOUSE_TRAP]: { name: "Mouse trap", unicode: "U+1FAA4", emoji: "🪤" },
  [HouseholdEmojis.RAZOR]: { name: "Razor", unicode: "U+1FA92", emoji: "🪒" },
  [HouseholdEmojis.LOTION_BOTTLE]: { name: "Lotion bottle", unicode: "U+1F9F4", emoji: "🧴" },
  [HouseholdEmojis.SAFETY_PIN]: { name: "Safety pin", unicode: "U+1F9F7", emoji: "🧷" },
  [HouseholdEmojis.BROOM]: { name: "Broom", unicode: "U+1F9F9", emoji: "🧹" },
  [HouseholdEmojis.BASKET]: { name: "Basket", unicode: "U+1F9FA", emoji: "🧺" },
  [HouseholdEmojis.ROLL_OF_PAPER]: { name: "Roll of paper", unicode: "U+1F9FB", emoji: "🧻" },
  [HouseholdEmojis.BUCKET]: { name: "Bucket", unicode: "U+1FAA3", emoji: "🪣" },
  [HouseholdEmojis.SOAP]: { name: "Soap", unicode: "U+1F9FC", emoji: "🧼" },
  [HouseholdEmojis.BUBBLES]: { name: "Bubbles", unicode: "U+1FAE7", emoji: "🫧" },
  [HouseholdEmojis.TOOTHBRUSH]: { name: "Toothbrush", unicode: "U+1FAA5", emoji: "🪥" },
  [HouseholdEmojis.SPONGE]: { name: "Sponge", unicode: "U+1F9FD", emoji: "🧽" },
  [HouseholdEmojis.FIRE_EXTINGUISHER]: { name: "Fire extinguisher", unicode: "U+1F9EF", emoji: "🧯" },
  [HouseholdEmojis.SHOPPING_CART]: { name: "Shopping cart", unicode: "U+1F6D2", emoji: "🛒" },
}
