import { EmojiDefinition } from "./types";

export enum SkyAndWeatherEmojis {
  NEW_MOON = "new_moon",
  WAXING_CRESCENT_MOON = "waxing_crescent_moon",
  FIRST_QUARTER_MOON = "first_quarter_moon",
  WAXING_GIBBOUS_MOON = "waxing_gibbous_moon",
  FULL_MOON = "full_moon",
  WANING_GIBBOUS_MOON = "waning_gibbous_moon",
  LAST_QUARTER_MOON = "last_quarter_moon",
  WANING_CRESCENT_MOON = "waning_crescent_moon",
  CRESCENT_MOON = "crescent_moon",
  NEW_MOON_FACE = "new_moon_face",
  FIRST_QUARTER_MOON_FACE = "first_quarter_moon_face",
  LAST_QUARTERMOON_FACE = "last_quartermoon_face",
  THERMOMETER = "thermometer",
  SUN = "sun",
  FULL_MOON_FACE = "full_moon_face",
  SUN_WITH_FACE = "sun_with_face",
  RINGED_PLANET = "ringed_planet",
  STAR = "star",
  GLOWING_STAR = "glowing_star",
  SHOOTING_STAR = "shooting_star",
  MILKY_WAY = "milky_way",
  CLOUD = "cloud",
  SUN_BEHIND_CLOUD = "sun_behind_cloud",
  CLOUD_WITH_LIGHTING_AND_RAIN = "cloud_with_liting_and_rain",
  SUN_BEHIND_SMALL_CLOUD = "sun_behind_small_cloud",
  SUN_BEHIND_LARGE_CLOUD = "sun_behind_large_cloud",
  SUN_BEHIND_RAIN_CLOUD = "sun_behind_rain_cloud",
  CLOUD_WITH_RAIN = "cloud_with_rain",
  CLOUD_WITH_SNOW = "cloud_with_snow",
  CLOUD_WITH_LIGHTING = "cloud_with_lighting",
  TORNADO = "tornado",
  FOG = "fog",
  WIND_FACE = "wind_face",
  CYCLONE = "cyclone",
  RAINBOW = "rainbow",
  CLOSED_UMBRELLA = "closed_umbrella",
  UMBRELLA = "umbrella",
  UMBRELLA_WITH_RAINDROPS = "umbrella_with_raindrops",
  UMBRELLA_ON_GROUND = "umbrella_on_ground",
  HIGH_VOLTAGE = "high_voltage",
  SNOWFLAKE = "snowflake",
  SNOWMAN = "snowman",
  SNOWMAN_WITHOUT_SNOW = "snowman_without_snow",
  COMET = "comet",
  FIRE = "fire",
  DROPLET = "droplet",
  WATER_WAVE = "water_wave",
}

export const skyAndWeatherEmojis: Record<SkyAndWeatherEmojis, EmojiDefinition> = {
  [SkyAndWeatherEmojis.NEW_MOON]: { name: "New moon", unicode: "U+1F311", emoji: "🌑" },
  [SkyAndWeatherEmojis.WAXING_CRESCENT_MOON]: { name: "Waxing crescent moon", unicode: "U+1F312", emoji: "🌒" },
  [SkyAndWeatherEmojis.FIRST_QUARTER_MOON]: { name: "First quarter moon", unicode: "U+1F313", emoji: "🌓" },
  [SkyAndWeatherEmojis.WAXING_GIBBOUS_MOON]: { name: "Waxing gibbous moon", unicode: "U+1F314", emoji: "🌔" },
  [SkyAndWeatherEmojis.FULL_MOON]: { name: "Full moon", unicode: "U+1F315", emoji: "🌕" },
  [SkyAndWeatherEmojis.WANING_GIBBOUS_MOON]: { name: "Waning gibbous moon", unicode: "U+1F316", emoji: "🌖" },
  [SkyAndWeatherEmojis.LAST_QUARTER_MOON]: { name: "Last quarter moon", unicode: "U+1F317", emoji: "🌗" },
  [SkyAndWeatherEmojis.WANING_CRESCENT_MOON]: { name: "Waning crescent moon", unicode: "U+1F318", emoji: "🌘" },
  [SkyAndWeatherEmojis.CRESCENT_MOON]: { name: "Crescent moon", unicode: "U+1F319", emoji: "🌙" },
  [SkyAndWeatherEmojis.NEW_MOON_FACE]: { name: "New moon face", unicode: "U+1F31A", emoji: "🌚" },
  [SkyAndWeatherEmojis.FIRST_QUARTER_MOON_FACE]: { name: "First quarter moon face", unicode: "U+1F31B", emoji: "🌛" },
  [SkyAndWeatherEmojis.LAST_QUARTERMOON_FACE]: { name: "Last quartermoon face", unicode: "U+1F31C", emoji: "🌜" },
  [SkyAndWeatherEmojis.THERMOMETER]: { name: "Thermometer", unicode: "U+1F321", emoji: "🌡" },
  [SkyAndWeatherEmojis.SUN]: { name: "Sun", unicode: "U+2600", emoji: "☀" },
  [SkyAndWeatherEmojis.FULL_MOON_FACE]: { name: "Full moon face", unicode: "U+1F31D", emoji: "🌝" },
  [SkyAndWeatherEmojis.SUN_WITH_FACE]: { name: "Sun with face", unicode: "U+1F31E", emoji: "🌞" },
  [SkyAndWeatherEmojis.RINGED_PLANET]: { name: "Ringed planet", unicode: "U+1FA90", emoji: "🪐" },
  [SkyAndWeatherEmojis.STAR]: { name: "Star", unicode: "U+2B50", emoji: "⭐" },
  [SkyAndWeatherEmojis.GLOWING_STAR]: { name: "Glowing star", unicode: "U+1F31F", emoji: "🌟" },
  [SkyAndWeatherEmojis.SHOOTING_STAR]: { name: "Shooting star", unicode: "U+1F320", emoji: "🌠" },
  [SkyAndWeatherEmojis.MILKY_WAY]: { name: "Milky way", unicode: "U+1F30C", emoji: "🌌" },
  [SkyAndWeatherEmojis.CLOUD]: { name: "Cloud", unicode: "U+2601", emoji: "☁" },
  [SkyAndWeatherEmojis.SUN_BEHIND_CLOUD]: { name: "Sun behind cloud", unicode: "U+26C5", emoji: "⛅" },
  [SkyAndWeatherEmojis.CLOUD_WITH_LIGHTING_AND_RAIN]: { name: "Cloud with lighting and rain", unicode: "U+26C8", emoji: "⛈" },
  [SkyAndWeatherEmojis.SUN_BEHIND_SMALL_CLOUD]: { name: "Sun behind small cloud", unicode: "U+1F324", emoji: "🌤" },
  [SkyAndWeatherEmojis.SUN_BEHIND_LARGE_CLOUD]: { name: "Sun behind large cloud", unicode: "U+1F325", emoji: "🌥" },
  [SkyAndWeatherEmojis.SUN_BEHIND_RAIN_CLOUD]: { name: "Sun behind rain cloud", unicode: "U+1F326", emoji: "🌦" },
  [SkyAndWeatherEmojis.CLOUD_WITH_RAIN]: { name: "Cloud with rain", unicode: "U+1F327", emoji: "🌧" },
  [SkyAndWeatherEmojis.CLOUD_WITH_SNOW]: { name: "Cloud with snow", unicode: "U+1F328", emoji: "🌨" },
  [SkyAndWeatherEmojis.CLOUD_WITH_LIGHTING]: { name: "Cloud with lighting", unicode: "U+1005", emoji: "🌩" },
  [SkyAndWeatherEmojis.TORNADO]: { name: "Tornado", unicode: "U+1F32A", emoji: "🌪" },
  [SkyAndWeatherEmojis.FOG]: { name: "Fog", unicode: "U+1F32B", emoji: "🌫" },
  [SkyAndWeatherEmojis.WIND_FACE]: { name: "Wind face", unicode: "U+1F32C", emoji: "🌬" },
  [SkyAndWeatherEmojis.CYCLONE]: { name: "Cyclone", unicode: "U+1F300", emoji: "🌀" },
  [SkyAndWeatherEmojis.RAINBOW]: { name: "Rainbow", unicode: "U+1F308", emoji: "🌈" },
  [SkyAndWeatherEmojis.CLOSED_UMBRELLA]: { name: "Closed umbrella", unicode: "U+1F302", emoji: "🌂" },
  [SkyAndWeatherEmojis.UMBRELLA]: { name: "Umbrella", unicode: "U+2602", emoji: "☂" },
  [SkyAndWeatherEmojis.UMBRELLA_WITH_RAINDROPS]: { name: "Umbrella with raindrops", unicode: "U+2614", emoji: "☔" },
  [SkyAndWeatherEmojis.UMBRELLA_ON_GROUND]: { name: "Umbrella on ground", unicode: "U+26F1", emoji: "⛱" },
  [SkyAndWeatherEmojis.HIGH_VOLTAGE]: { name: "High voltage", unicode: "U+26A1", emoji: "⚡" },
  [SkyAndWeatherEmojis.SNOWFLAKE]: { name: "Snowflake", unicode: "U+2744", emoji: "❄" },
  [SkyAndWeatherEmojis.SNOWMAN]: { name: "Snowman", unicode: "U+2603", emoji: "☃" },
  [SkyAndWeatherEmojis.SNOWMAN_WITHOUT_SNOW]: { name: "Snowman without snow", unicode: "U+26C4", emoji: "⛄" },
  [SkyAndWeatherEmojis.COMET]: { name: "Comet", unicode: "U+2604", emoji: "☄" },
  [SkyAndWeatherEmojis.FIRE]: { name: "Fire", unicode: "U+1F525", emoji: "🔥" },
  [SkyAndWeatherEmojis.DROPLET]: { name: "Droplet", unicode: "U+1F4A7", emoji: "💧" },
  [SkyAndWeatherEmojis.WATER_WAVE]: { name: "Water wave", unicode: "U+1F30A", emoji: "🌊" },
}
