import { EmojiDefinition } from "./types";

export enum SportEmojis {
  SOCCER_BALL = "soccer_ball",
  BASEBALL = "baseball",
  SOFTBALL = "softball",
  BASKETBALL = "basketball",
  VOLLEYBALL = "volleyball",
  AMERICAN_FOOTBALL = "american_football",
  RUGBY = "rugby",
  TENNIS = "tennis",
  FLYING_DISK = "flying_disk",
  BOWLING = "bowling",
  CRICKET = "cricket",
  FIELD_HOCKEY = "field_hockey",
  ICE_HOCKEY = "ice_hockey",
  LACROSSE = "lacrosse",
  PING_PONG = "ping_pong",
  BADMINTON = "badminton",
  BOXING_GLOVE = "boxing_glove",
  MARTIAL_ARTS_UNIFORM = "martial_arts_uniform",
  GOAL_NET = "goal_net",
  FLAG_IN_HOLE = "flag_in_hole",
  ICE_SKATE = "ice_skate",
  FISHING_POLE = "fishing_pole",
  DIVING_MASK = "diving_mask",
  RUNNING_SHIRT = "running_shirt",
  SKIS = "skis",
  SLED = "sled",
  CURLING_STONE = "curling_stone",
}

export const sportEmojis: Record<SportEmojis, EmojiDefinition> = {
  [SportEmojis.SOCCER_BALL]: { name: "Soccer ball", unicode: "U+26BD", emoji: "⚽" },
  [SportEmojis.BASEBALL]: { name: "Baseball", unicode: "U+26BE", emoji: "⚾" },
  [SportEmojis.SOFTBALL]: { name: "Softball", unicode: "U+1F94E", emoji: "🥎" },
  [SportEmojis.BASKETBALL]: { name: "Basketball", unicode: "U+1F3C0", emoji: "🏀" },
  [SportEmojis.VOLLEYBALL]: { name: "Volleyball", unicode: "U+1F3D0", emoji: "🏐" },
  [SportEmojis.AMERICAN_FOOTBALL]: { name: "American football", unicode: "U+1F3C8", emoji: "🏈" },
  [SportEmojis.RUGBY]: { name: "Rugby", unicode: "U+1F3C9", emoji: "🏉" },
  [SportEmojis.TENNIS]: { name: "Tennis", unicode: "U+1F3BE", emoji: "🎾" },
  [SportEmojis.FLYING_DISK]: { name: "Flying disk", unicode: "U+1F94F", emoji: "🥏" },
  [SportEmojis.BOWLING]: { name: "Bowling", unicode: "U+1F3B3", emoji: "🎳" },
  [SportEmojis.CRICKET]: { name: "Cricket", unicode: "U+1F3CF", emoji: "🏏" },
  [SportEmojis.FIELD_HOCKEY]: { name: "Field hockey", unicode: "U+1F3D1", emoji: "🏑" },
  [SportEmojis.ICE_HOCKEY]: { name: "Ice hockey", unicode: "U+1F3D2", emoji: "🏒" },
  [SportEmojis.LACROSSE]: { name: "Lacrosse", unicode: "U+1F94D", emoji: "🥍" },
  [SportEmojis.PING_PONG]: { name: "Ping pong", unicode: "U+1F3D3", emoji: "🏓" },
  [SportEmojis.BADMINTON]: { name: "Badminton", unicode: "U+1F3F8", emoji: "🏸" },
  [SportEmojis.BOXING_GLOVE]: { name: "Boxing glove", unicode: "U+1F94A", emoji: "🥊" },
  [SportEmojis.MARTIAL_ARTS_UNIFORM]: { name: "Martial arts uniform", unicode: "U+1F94B", emoji: "🥋" },
  [SportEmojis.GOAL_NET]: { name: "Goal net", unicode: "U+1F945", emoji: "🥅" },
  [SportEmojis.FLAG_IN_HOLE]: { name: "Flag in a hole", unicode: "U+26F3", emoji: "⛳" },
  [SportEmojis.ICE_SKATE]: { name: "Ice skate", unicode: "U+26F8", emoji: "⛸" },
  [SportEmojis.FISHING_POLE]: { name: "Fishing pole", unicode: "U+1F3A3", emoji: "🎣" },
  [SportEmojis.DIVING_MASK]: { name: "Diving mask", unicode: "U+1F93F", emoji: "🤿" },
  [SportEmojis.RUNNING_SHIRT]: { name: "Running shirt", unicode: "U+1F3BD", emoji: "🎽" },
  [SportEmojis.SKIS]: { name: "Skis", unicode: "U+1F3BF", emoji: "🎿" },
  [SportEmojis.SLED]: { name: "Sled", unicode: "U+1F6F7", emoji: "🛷" },
  [SportEmojis.CURLING_STONE]: { name: "Curling stone", unicode: "U+1F94C", emoji: "🥌" },
}
