import { type EmojiDefinition } from "./types";

export enum TransportEmojis {
  LOCOMOTIVE = "locomotive",
  RAILWAY_CAR = "railway_car",
  HIGH_SPEED_TRAIN = "high_speed_train",
  BULLET_TRAIN = "bullet_train",
  TRAIN = "train",
  METRO = "metro",
  LIGHT_RAIL = "light_rail",
  STATION = "station",
  TRAM = "tram",
  MONORAIL = "monorail",
  MOUNTAIN_RAILWAY = "mountain_railway",
  TRAM_CAR = "tram_car",
  BUS = "bus",
  ONCOMING_BUS = "oncoming_bus",
  TROLLEY_BUS = "trolley_bus",
  MINIBUS = "minibus",
  AMBULANCE = "ambulance",
  FIRE_ENGINE = "fire_engine",
  POLICE_CAR = "police_car",
  ONCOMING_POLICE_CAR = "oncoming_police_car",
  TAXI = "taxi",
  ONCOMING_TAXI = "oncoming_taxi",
  AUTOMOBILE = "automobile",
  ONCOMING_AUTOMOBILE = "oncoming_automobile",
  SPORT_UTILITY_VEHICLE = "sport_utility_vehicle",
  PICKUP_TRUCK = "pickup_truck",
  DELIVERY_TRUCK = "delivery_truck",
  ARTICULATED_LORRY = "articulated_lorry",
  TRACTOR = "tractor",
  RACING_CAR = "racing_car",
  MOTORCYCLE = "motorcycle",
  SCOOTER = "scooter",
  MANUAL_WHEELCHAIR = "manual_wheelchair",
  MOTORIZED_WHEELCHAIR = "motorized_wheelchair",
}

export const transportEmojis: Record<TransportEmojis, EmojiDefinition> = {
  [TransportEmojis.LOCOMOTIVE]: { name: "Locomotive", unicode: "U+1F682", emoji: "🚂" },
  [TransportEmojis.RAILWAY_CAR]: { name: "Railway car", unicode: "U+1F683", emoji: "🚃" },
  [TransportEmojis.HIGH_SPEED_TRAIN]: { name: "High speed train", unicode: "U+1F684", emoji: "🚄" },
  [TransportEmojis.BULLET_TRAIN]: { name: "Bullet train", unicode: "U+1F685", emoji: "🚅" },
  [TransportEmojis.TRAIN]: { name: "Train", unicode: "U+1F686", emoji: "🚆" },
  [TransportEmojis.METRO]: { name: "Metro", unicode: "U+1F687", emoji: "🚇" },
  [TransportEmojis.LIGHT_RAIL]: { name: "Light rail", unicode: "U+1F688", emoji: "🚈" },
  [TransportEmojis.STATION]: { name: "Station", unicode: "U+1F689", emoji: "🚉" },
  [TransportEmojis.TRAM]: { name: "Tram", unicode: "U+1F68A", emoji: "🚊" },
  [TransportEmojis.MONORAIL]: { name: "Monorail", unicode: "U+1F69D", emoji: "🚝" },
  [TransportEmojis.MOUNTAIN_RAILWAY]: { name: "Mountain railway", unicode: "U+1F69E", emoji: "🚞" },
  [TransportEmojis.TRAM_CAR]: { name: "Tram car", unicode: "U+1F68B", emoji: "🚋" },
  [TransportEmojis.BUS]: { name: "us", unicode: "U+1F68C", emoji: "🚌" },
  [TransportEmojis.ONCOMING_BUS]: { name: "Oncoming bus", unicode: "U+1F68D", emoji: "🚍" },
  [TransportEmojis.TROLLEY_BUS]: { name: "Trolley bus", unicode: "U+1F68E", emoji: "🚎" },
  [TransportEmojis.MINIBUS]: { name: "Minibus", unicode: "U+1F690", emoji: "🚐" },
  [TransportEmojis.AMBULANCE]: { name: "Ambulance", unicode: "U+1F691", emoji: "🚑" },
  [TransportEmojis.FIRE_ENGINE]: { name: "Fire engine", unicode: "U+1F692", emoji: "🚒" },
  [TransportEmojis.POLICE_CAR]: { name: "Police car", unicode: "U+1F693", emoji: "🚓" },
  [TransportEmojis.ONCOMING_POLICE_CAR]: { name: "Oncoming police car", unicode: "U+1F694", emoji: "🚔" },
  [TransportEmojis.TAXI]: { name: "Taxi", unicode: "U+1F695", emoji: "🚕" },
  [TransportEmojis.ONCOMING_TAXI]: { name: "Oncoming taxi", unicode: "U+1F696", emoji: "🚖" },
  [TransportEmojis.AUTOMOBILE]: { name: "Automobile", unicode: "U+1F697", emoji: "🚗" },
  [TransportEmojis.ONCOMING_AUTOMOBILE]: { name: "Oncoming automobile", unicode: "U+1F698", emoji: "🚘" },
  [TransportEmojis.SPORT_UTILITY_VEHICLE]: { name: "Sport utility vehicle", unicode: "U+1F699", emoji: "🚙" },
  [TransportEmojis.PICKUP_TRUCK]: { name: "Pickup truck", unicode: "U+1F6FB", emoji: "🛻" },
  [TransportEmojis.DELIVERY_TRUCK]: { name: "Delivery truck", unicode: "U+1F69A", emoji: "🚚" },
  [TransportEmojis.ARTICULATED_LORRY]: { name: "Articulated lorry", unicode: "U+1F69B", emoji: "🚛" },
  [TransportEmojis.TRACTOR]: { name: "Tractor", unicode: "U+1F69C", emoji: "🚜" },
  [TransportEmojis.RACING_CAR]: { name: "Racing car", unicode: "U+1F3CE", emoji: "🏎" },
  [TransportEmojis.MOTORCYCLE]: { name: "Motorcycle", unicode: "U+1F3CD", emoji: "🏍" },
  [TransportEmojis.SCOOTER]: { name: "Scooter", unicode: "U+1F6F5", emoji: "🛵" },
  [TransportEmojis.MANUAL_WHEELCHAIR]: { name: "Manual wheelchair", unicode: "U+1F9BD", emoji: "🦽" },
  [TransportEmojis.MOTORIZED_WHEELCHAIR]: { name: "Motorized wheelchair", unicode: "U+1F9BC", emoji: "🦼" },
}
