import { type EmojiDefinition } from "./types";

export enum TravelAndPlacesEmojis {
  GLOBE_SHOWING_AFRICA_EUROPE = "globe_showing_africa_europe",
  GLOBE_SHOWING_AMERICAS = "globe_showing_americas",
  GLOBE_SHOWING_ASIA_AUSTRALIA = "globe_showing_asia_australia",
  GLOBE_WITH_MERIDIANS = "globe_with_meridians",
  WORLD_MAP = "world_map",
  COMPASS = "compass",
  MOUNTAIN = "mountain",
  SNOWCAP_MOUNTAIN = "snowcap_mountain",
  VOLCANIC_MOUNTAIN = "volcanic_mountain",
  FUJI_MOUNTAIN = "fuji_mountain",
  CAMPING = "camping",
  BEACH_WITH_UMBRELLA = "beach_with_umbrella",
  DESERT = "desert",
  DESERTIFIED_ISLAND = "desertified_island",
  NATIONAL_PARK = "national_park",
  STADIUM = "stadium",
  CLASSICAL_BUILDING = "classical_building",
  BUILDING_CONSTRUCTION = "building_construction",
  BRICK = "brick",
  ROCK = "rock",
  WOOD = "wood",
  HUT = "hut",
  HOUSES = "houses",
  DERELICT_HOUSE = "derelict_house",
  HOUSE = "house",
  HOUSE_WITH_GARDEN = "house_with_garden",
  OFFICE_BUILDING = "office_building",
  JAPANESE_OFFICE = "japanese_office",
  POST_OFFICE = "post_office",
  HOSPITAL = "hospital",
  BANK = "bank",
  HOTEL = "hotel",
  LOVE_HOTEL = "love_hotel",
  CONVENIENCE_STORE = "convenience_store",
  SCHOOL = "school",
  DEPARTMENT = "department",
  FACTORY = "factory",
  JAPANESE_CASTLE = "japanese_castle",
  CASTLE = "castle",
  WEDDING_HOUSE = "wedding_house",
  TOKYO_TOWER = "tokyo_tower",
  STATUE_OF_LIBERTY = "statue_of_liberty",
  CHURCH = "church",
  MOSQUE = "mosque",
  HINDU_TEMPLE = "hindu_temple",
  SYNAGOGUE = "synagogue",
  SHINTO_SHRINE = "shinto_shrine",
  KAABA = "kaaba",
  FOUNTAIN = "fountain",
  TENT = "tent",
  FOGGY = "foggy",
  NIGHT_WITH_STARRS = "night_with_starrs",
  CITYSCAPE = "cityscape",
  SUNRISE = "sunrise",
  SUNRISE_OVER_MOUNTAINS = "sunrise_over_mountains",
  CITYSCAPE_AT_DUSK = "cityscape_at_dusk",
  SUNSET = "sunset",
  BRIDGE_AT_NIGHT = "bridge_at_night",
  HOT_SPRINGS = "hot_springs",
  CAROUSEL_HORSE = "carousel_horse",
  FERRIS_WHEEL = "ferris_wheel",
  ROLLER_COASTER = "roller_coaster",
  BARBER_POLL = "barber_poll",
  CIRCUS_TENT = "circus_tent",
}

export const travelAndPlacesEmojis: Record<TravelAndPlacesEmojis, EmojiDefinition> = {
  [TravelAndPlacesEmojis.GLOBE_SHOWING_AFRICA_EUROPE]: { name: "Globe showing Africa and Europe", unicode: "U+1F30D", emoji: "🌍" },
  [TravelAndPlacesEmojis.GLOBE_SHOWING_AMERICAS]: { name: "Globe showing Americas", unicode: "U+1F30E", emoji: "🌎" },
  [TravelAndPlacesEmojis.GLOBE_SHOWING_ASIA_AUSTRALIA]: { name: "Globe showing Asia and Australia", unicode: "U+1F30F", emoji: "🌏" },
  [TravelAndPlacesEmojis.GLOBE_WITH_MERIDIANS]: { name: "Globe with meridians", unicode: "U+1F310", emoji: "🌐" },
  [TravelAndPlacesEmojis.WORLD_MAP]: { name: "World map", unicode: "U+1F5FA", emoji: "🗺" },
  [TravelAndPlacesEmojis.COMPASS]: { name: "Compass", unicode: "U+1F9ED", emoji: "🧭" },
  [TravelAndPlacesEmojis.MOUNTAIN]: { name: "Mountain", unicode: "U+26F0", emoji: "⛰" },
  [TravelAndPlacesEmojis.SNOWCAP_MOUNTAIN]: { name: "Snowcap mountain", unicode: "U+26F0", emoji: "🏔" },
  [TravelAndPlacesEmojis.VOLCANIC_MOUNTAIN]: { name: "Volcanic mountain", unicode: "U+1F30B", emoji: "🌋" },
  [TravelAndPlacesEmojis.FUJI_MOUNTAIN]: { name: "Fuji mountain", unicode: "U+1F5FB", emoji: "🗻" },
  [TravelAndPlacesEmojis.CAMPING]: { name: "Camping", unicode: "U+1F3D5", emoji: "🏕" },
  [TravelAndPlacesEmojis.BEACH_WITH_UMBRELLA]: { name: "Beach with umbrella", unicode: "U+1F3D6", emoji: "🏖" },
  [TravelAndPlacesEmojis.DESERT]: { name: "Desert", unicode: "U+1F3DC", emoji: "🏜" },
  [TravelAndPlacesEmojis.DESERTIFIED_ISLAND]: { name: "Desertified island", unicode: "U+1F3DD", emoji: "🏝" },
  [TravelAndPlacesEmojis.NATIONAL_PARK]: { name: "National park", unicode: "U+1F3DE", emoji: "🏞" },
  [TravelAndPlacesEmojis.STADIUM]: { name: "Stadium", unicode: "U+1F3DF", emoji: "🏟" },
  [TravelAndPlacesEmojis.CLASSICAL_BUILDING]: { name: "Classical building", unicode: "U+1F3DB", emoji: "🏛" },
  [TravelAndPlacesEmojis.BUILDING_CONSTRUCTION]: { name: "Building construction", unicode: "U+1F3D7", emoji: "🏗" },
  [TravelAndPlacesEmojis.BRICK]: { name: "Brick", unicode: "U+1F9F1", emoji: "🧱" },
  [TravelAndPlacesEmojis.ROCK]: { name: "Rock", unicode: "U+1FAA8", emoji: "🪨" },
  [TravelAndPlacesEmojis.WOOD]: { name: "Wood", unicode: "U+1FAB5", emoji: "🪵" },
  [TravelAndPlacesEmojis.HUT]: { name: "Hut", unicode: "U+1F6D6", emoji: "🛖" },
  [TravelAndPlacesEmojis.HOUSES]: { name: "Houses", unicode: "U+1F3D8", emoji: "🏘" },
  [TravelAndPlacesEmojis.DERELICT_HOUSE]: { name: "Derelict house", unicode: "U+1F3DA", emoji: "🏚" },
  [TravelAndPlacesEmojis.HOUSE]: { name: "House", unicode: "U+1F3E0", emoji: "🏠" },
  [TravelAndPlacesEmojis.HOUSE_WITH_GARDEN]: { name: "House with garden", unicode: "U+1F3E1", emoji: "🏡" },
  [TravelAndPlacesEmojis.OFFICE_BUILDING]: { name: "Office building", unicode: "U+1F3E2", emoji: "🏢" },
  [TravelAndPlacesEmojis.JAPANESE_OFFICE]: { name: "Japanese office", unicode: "U+1F3E3", emoji: "🏣" },
  [TravelAndPlacesEmojis.POST_OFFICE]: { name: "Post office", unicode: "U+1F3E4", emoji: "🏤" },
  [TravelAndPlacesEmojis.HOSPITAL]: { name: "Hospital", unicode: "U+1F3E5", emoji: "🏥" },
  [TravelAndPlacesEmojis.BANK]: { name: "Bank", unicode: "U+1F3E6", emoji: "🏦" },
  [TravelAndPlacesEmojis.HOTEL]: { name: "Hotel", unicode: "U+1F3E8", emoji: "🏨" },
  [TravelAndPlacesEmojis.LOVE_HOTEL]: { name: "Love hotel", unicode: "U+1F3E9", emoji: "🏩" },
  [TravelAndPlacesEmojis.CONVENIENCE_STORE]: { name: "Convenience store", unicode: "U+1F3EA", emoji: "🏪" },
  [TravelAndPlacesEmojis.SCHOOL]: { name: "School", unicode: "U+1F3EB", emoji: "🏫" },
  [TravelAndPlacesEmojis.DEPARTMENT]: { name: "Department", unicode: "U+1F3EC", emoji: "🏬" },
  [TravelAndPlacesEmojis.FACTORY]: { name: "Factory", unicode: "U+1F3ED", emoji: "🏭" },
  [TravelAndPlacesEmojis.JAPANESE_CASTLE]: { name: "Japanese castle", unicode: "U+1F3EF", emoji: "🏯" },
  [TravelAndPlacesEmojis.CASTLE]: { name: "Castle", unicode: "U+1F3F0", emoji: "🏰" },
  [TravelAndPlacesEmojis.WEDDING_HOUSE]: { name: "Wedding house", unicode: "U+1F492", emoji: "💒" },
  [TravelAndPlacesEmojis.TOKYO_TOWER]: { name: "Tokyo tower", unicode: "U+1F5FC", emoji: "🗼" },
  [TravelAndPlacesEmojis.STATUE_OF_LIBERTY]: { name: "Statue of liberty", unicode: "U+1F5FD", emoji: "🗽" },
  [TravelAndPlacesEmojis.CHURCH]: { name: "Church", unicode: "U+26EA", emoji: "⛪" },
  [TravelAndPlacesEmojis.MOSQUE]: { name: "Mosque", unicode: "U+1F54C", emoji: "🕌" },
  [TravelAndPlacesEmojis.HINDU_TEMPLE]: { name: "Hindu temple", unicode: "U+1F6D5", emoji: "🛕" },
  [TravelAndPlacesEmojis.SYNAGOGUE]: { name: "Synagogue", unicode: "U+1F54D", emoji: "🕍" },
  [TravelAndPlacesEmojis.SHINTO_SHRINE]: { name: "Shinto shrine", unicode: "U+26E9", emoji: "⛩" },
  [TravelAndPlacesEmojis.KAABA]: { name: "Kaaba", unicode: "U+1F54B", emoji: "🕋" },
  [TravelAndPlacesEmojis.FOUNTAIN]: { name: "Fountain", unicode: "U+26F2", emoji: "⛲" },
  [TravelAndPlacesEmojis.TENT]: { name: "Tent", unicode: "U+26FA", emoji: "⛺" },
  [TravelAndPlacesEmojis.FOGGY]: { name: "Foggy", unicode: "U+1F301", emoji: "🌁" },
  [TravelAndPlacesEmojis.NIGHT_WITH_STARRS]: { name: "Night with starrs", unicode: "U+1F303", emoji: "🌃" },
  [TravelAndPlacesEmojis.CITYSCAPE]: { name: "Citscape", unicode: "U+1F3D9", emoji: "🏙" },
  [TravelAndPlacesEmojis.SUNRISE]: { name: "Sunrise", unicode: "U+1F305", emoji: "🌅" },
  [TravelAndPlacesEmojis.SUNRISE_OVER_MOUNTAINS]: { name: "Sunrise over mountains", unicode: "U+1F304", emoji: "🌄" },
  [TravelAndPlacesEmojis.CITYSCAPE_AT_DUSK]: { name: "Cityscape at dusk", unicode: "U+1F306", emoji: "🌆" },
  [TravelAndPlacesEmojis.SUNSET]: { name: "Sunset", unicode: "U+1F307", emoji: "🌇" },
  [TravelAndPlacesEmojis.BRIDGE_AT_NIGHT]: { name: "Bridge at night", unicode: "U+1F309", emoji: "🌉" },
  [TravelAndPlacesEmojis.HOT_SPRINGS]: { name: "Hot springs", unicode: "U+2668", emoji: "♨" },
  [TravelAndPlacesEmojis.CAROUSEL_HORSE]: { name: "Carousel horse", unicode: "U+1F3A0", emoji: "🎠" },
  [TravelAndPlacesEmojis.FERRIS_WHEEL]: { name: "Ferris wheel", unicode: "U+1F3A1", emoji: "🎡" },
  [TravelAndPlacesEmojis.ROLLER_COASTER]: { name: "Roller coaster", unicode: "U+1F3A2", emoji: "🎢" },
  [TravelAndPlacesEmojis.BARBER_POLL]: { name: "Barber poll", unicode: "U+1F488", emoji: "💈" },
  [TravelAndPlacesEmojis.CIRCUS_TENT]: { name: "Circus tent", unicode: "U+1F3AA", emoji: "🎪" },
}
